#include<stdio.h>

int check(int x, int a, int b, int c, int d)
{
    int pin=0;
    if(a+b+c+d==x) pin=1;
    else if(a+b+c-d==x) pin=1;
    else if(a+b-c+d==x) pin=1;
    else if(a-b+c+d==x) pin=1;
    else if(a+b-c-d==x) pin=1;
    else if(a-b+c-d==x) pin=1;
    else if(a-b-c+d==x) pin=1;
    else if(a-b-c-d==x) pin=1;
    else if(a*b*c*d==x) pin=1;
    else if(a/b/c/d==x && a%b==0 && (a/b)%c==0 && (a/b/c)%d==0) pin=1;
    else if((a+b+c)*d==x) pin=1;
    else if((a+b)*c+d==x) pin=1;
    else if(a*b+c+d==x) pin=1;
    else if(a*b*c+d==x) pin=1;
    else if((a*b+c)*d==x) pin=1;
    else if((a+b)*c*d==x) pin=1;
    else if(a*b*c-d==x) pin=1;
    else if((a*b-c)*d==x) pin=1;
    else if((a-b)*c*d==x) pin=1;
    else if(a*b-c-d==x) pin=1;
    else if((a-b)*c-d==x) pin=1;
    else if((a-b-c)*d==x) pin=1;
    else if(a/b+c+d==x && a%b==0) pin=1;
    else if((a+b)/c+d==x && (a+b)%c==0) pin=1;
    else if((a+b+c)/d==x && (a+b+c)%d==0) pin=1;
    else if(a/b/c+d==x && a%b==0 && (a/b)%c==0) pin=1;
    else if((a/b+c)/d==x && a%b==0 && (a/b+c)%d==0) pin=1;
    else if((a+b)/c/d==x && (a+b)%c==0 && ((a+b)/c)%d==0) pin=1;
    else if(a/b-c-d==x && a%b==0) pin=1;
    else if((a-b)/c-d==x && (a-b)%c==0) pin=1;
    else if((a-b-c)/d==x && (a-b-c)%d==0) pin=1;
    else if(a/b/c-d==x && a%b==0 && (a/b)%c==0) pin=1;
    else if((a/b-c)/d==x && a%b==0 && (a/b-c)%d==0) pin=1;
    else if((a-b)/c/d==x && (a-b)%c==0 && ((a-b)/c)%d==0) pin=1;
    else if(a/b*c*d==x && a%b==0) pin=1;
    else if(a*b/c*d==x && (a*b)%c==0) pin=1;
    else if(a*b*c/d==x && (a*b*c)%d==0) pin=1;
    else if(a*b/c/d==x && (a*b)%c==0 && (a*b/c)%d==0) pin=1;
    else if(a/b*c/d==x && a%b==0 && (a/b*c)%d==0) pin=1;
    else if(a/b/c*d==x && a%b==0 && (a/b)%c==0) pin=1;
    else if((a+b-c)*d==x) pin=1;
    else if((a-b)*c+d==x) pin=1;
    else if(a*b-c+d==x) pin=1;
    else if((a+b)*c-d==x) pin=1;
    else if(a*b+c-d==x) pin=1;
    else if((a-b+c)*d==x) pin=1;
    else if((a-b)*c/d==x && ((a-b)*c)%d==0) pin=1;
    else if(a*b/c-d==x && (a*b)%c==0) pin=1;
    else if((a/b-c)*d==x && a%b==0) pin=1;
    else if((a-b)/c*d==x && (a-b)%c==0) pin=1;
    else if(a/b*c-d==x && a%b==0) pin=1;
    else if((a*b-c)/d==x && (a*b-c)%d==0) pin=1;
    else if(a*b/c+d==x && (a*b)%c==0) pin=1;
    else if((a/b+c)*d==x && a%b==0) pin=1;
    else if((a+b)/c*d==x && (a+b)%c==0) pin=1;
    else if((a*b+c)/d==x && (a*b+c)%d==0) pin=1;
    else if((a+b)*c/d==x && ((a+b)*c)%d==0) pin=1;
    else if(a/b*c+d==x && a%b==0) pin=1;
    else if((a+b)/c-d==x && (a+b)%c==0) pin=1;
    else if((a-b)/c+d==x && (a-b)%c==0) pin=1;
    else if(a/b-c+d==x && a%b==0) pin=1;
    else if((a-b+c)/d==x && (a-b+c)%d==0) pin=1;
    else if((a+b-c)/d==x && (a+b-c)%d==0) pin=1;
    else if(a/b+c-d==x && a%b==0) pin=1;
    else if(a+b+d-c==x) pin=1;
    else if(a+b-d+c==x) pin=1;
    else if(a-b+d+c==x) pin=1;
    else if(a+b-d-c==x) pin=1;
    else if(a-b+d-c==x) pin=1;
    else if(a-b-d+c==x) pin=1;
    else if(a-b-d-c==x) pin=1;
    else if(a*b*d*c==x) pin=1;
    else if(a/b/d/c==x && a%b==0 && (a/b)%d==0 && (a/b/d)%c==0) pin=1;
    else if((a+b+d)*c==x) pin=1;
    else if((a+b)*d+c==x) pin=1;
    else if(a*b+d+c==x) pin=1;
    else if(a*b*d+c==x) pin=1;
    else if((a*b+d)*c==x) pin=1;
    else if((a+b)*d*c==x) pin=1;
    else if(a*b*d-c==x) pin=1;
    else if((a*b-d)*c==x) pin=1;
    else if((a-b)*d*c==x) pin=1;
    else if(a*b-d-c==x) pin=1;
    else if((a-b)*d-c==x) pin=1;
    else if((a-b-d)*c==x) pin=1;
    else if(a/b+d+c==x && a%b==0) pin=1;
    else if((a+b)/d+c==x && (a+b)%d==0) pin=1;
    else if((a+b+d)/c==x && (a+b+d)%c==0) pin=1;
    else if(a/b/d+c==x && a%b==0 && (a/b)%d==0) pin=1;
    else if((a/b+d)/c==x && a%b==0 && (a/b+d)%c==0) pin=1;
    else if((a+b)/d/c==x && (a+b)%d==0 && ((a+b)/d)%c==0) pin=1;
    else if(a/b-d-c==x && a%b==0) pin=1;
    else if((a-b)/d-c==x && (a-b)%d==0) pin=1;
    else if((a-b-d)/c==x && (a-b-d)%c==0) pin=1;
    else if(a/b/d-c==x && a%b==0 && (a/b)%d==0) pin=1;
    else if((a/b-d)/c==x && a%b==0 && (a/b-d)%c==0) pin=1;
    else if((a-b)/d/c==x && (a-b)%d==0 && ((a-b)/d)%c==0) pin=1;
    else if(a/b*d*c==x && a%b==0) pin=1;
    else if(a*b/d*c==x && (a*b)%d==0) pin=1;
    else if(a*b*d/c==x && (a*b*d)%c==0) pin=1;
    else if(a*b/d/c==x && (a*b)%d==0 && (a*b/d)%c==0) pin=1;
    else if(a/b*d/c==x && a%b==0 && (a/b*d)%c==0) pin=1;
    else if(a/b/d*c==x && a%b==0 && (a/b)%d==0) pin=1;
    else if((a+b-d)*c==x) pin=1;
    else if((a-b)*d+c==x) pin=1;
    else if(a*b-d+c==x) pin=1;
    else if((a+b)*d-c==x) pin=1;
    else if(a*b+d-c==x) pin=1;
    else if((a-b+d)*c==x) pin=1;
    else if((a-b)*d/c==x && ((a-b)*d)%c==0) pin=1;
    else if(a*b/d-c==x && (a*b)%d==0) pin=1;
    else if((a/b-d)*c==x && a%b==0) pin=1;
    else if((a-b)/d*c==x && (a-b)%d==0) pin=1;
    else if(a/b*d-c==x && a%b==0) pin=1;
    else if((a*b-d)/c==x && (a*b-d)%c==0) pin=1;
    else if(a*b/d+c==x && (a*b)%d==0) pin=1;
    else if((a/b+d)*c==x && a%b==0) pin=1;
    else if((a+b)/d*c==x && (a+b)%d==0) pin=1;
    else if((a*b+d)/c==x && (a*b+d)%c==0) pin=1;
    else if((a+b)*d/c==x && ((a+b)*d)%c==0) pin=1;
    else if(a/b*d+c==x && a%b==0) pin=1;
    else if((a+b)/d-c==x && (a+b)%d==0) pin=1;
    else if((a-b)/d+c==x && (a-b)%d==0) pin=1;
    else if(a/b-d+c==x && a%b==0) pin=1;
    else if((a-b+d)/c==x && (a-b+d)%c==0) pin=1;
    else if((a+b-d)/c==x && (a+b-d)%c==0) pin=1;
    else if(a/b+d-c==x && a%b==0) pin=1;
    else if(a+c+b-d==x) pin=1;
    else if(a+c-b+d==x) pin=1;
    else if(a-c+b+d==x) pin=1;
    else if(a+c-b-d==x) pin=1;
    else if(a-c+b-d==x) pin=1;
    else if(a-c-b+d==x) pin=1;
    else if(a-c-b-d==x) pin=1;
    else if(a*c*b*d==x) pin=1;
    else if(a/c/b/d==x && a%c==0 && (a/c)%b==0 && (a/c/b)%d==0) pin=1;
    else if((a+c+b)*d==x) pin=1;
    else if((a+c)*b+d==x) pin=1;
    else if(a*c+b+d==x) pin=1;
    else if(a*c*b+d==x) pin=1;
    else if((a*c+b)*d==x) pin=1;
    else if((a+c)*b*d==x) pin=1;
    else if(a*c*b-d==x) pin=1;
    else if((a*c-b)*d==x) pin=1;
    else if((a-c)*b*d==x) pin=1;
    else if(a*c-b-d==x) pin=1;
    else if((a-c)*b-d==x) pin=1;
    else if((a-c-b)*d==x) pin=1;
    else if(a/c+b+d==x && a%c==0) pin=1;
    else if((a+c)/b+d==x && (a+c)%b==0) pin=1;
    else if((a+c+b)/d==x && (a+c+b)%d==0) pin=1;
    else if(a/c/b+d==x && a%c==0 && (a/c)%b==0) pin=1;
    else if((a/c+b)/d==x && a%c==0 && (a/c+b)%d==0) pin=1;
    else if((a+c)/b/d==x && (a+c)%b==0 && ((a+c)/b)%d==0) pin=1;
    else if(a/c-b-d==x && a%c==0) pin=1;
    else if((a-c)/b-d==x && (a-c)%b==0) pin=1;
    else if((a-c-b)/d==x && (a-c-b)%d==0) pin=1;
    else if(a/c/b-d==x && a%c==0 && (a/c)%b==0) pin=1;
    else if((a/c-b)/d==x && a%c==0 && (a/c-b)%d==0) pin=1;
    else if((a-c)/b/d==x && (a-c)%b==0 && ((a-c)/b)%d==0) pin=1;
    else if(a/c*b*d==x && a%c==0) pin=1;
    else if(a*c/b*d==x && (a*c)%b==0) pin=1;
    else if(a*c*b/d==x && (a*c*b)%d==0) pin=1;
    else if(a*c/b/d==x && (a*c)%b==0 && (a*c/b)%d==0) pin=1;
    else if(a/c*b/d==x && a%c==0 && (a/c*b)%d==0) pin=1;
    else if(a/c/b*d==x && a%c==0 && (a/c)%b==0) pin=1;
    else if((a+c-b)*d==x) pin=1;
    else if((a-c)*b+d==x) pin=1;
    else if(a*c-b+d==x) pin=1;
    else if((a+c)*b-d==x) pin=1;
    else if(a*c+b-d==x) pin=1;
    else if((a-c+b)*d==x) pin=1;
    else if((a-c)*b/d==x && ((a-c)*b)%d==0) pin=1;
    else if(a*c/b-d==x && (a*c)%b==0) pin=1;
    else if((a/c-b)*d==x && a%c==0) pin=1;
    else if((a-c)/b*d==x && (a-c)%b==0) pin=1;
    else if(a/c*b-d==x && a%c==0) pin=1;
    else if((a*c-b)/d==x && (a*c-b)%d==0) pin=1;
    else if(a*c/b+d==x && (a*c)%b==0) pin=1;
    else if((a/c+b)*d==x && a%c==0) pin=1;
    else if((a+c)/b*d==x && (a+c)%b==0) pin=1;
    else if((a*c+b)/d==x && (a*c+b)%d==0) pin=1;
    else if((a+c)*b/d==x && ((a+c)*b)%d==0) pin=1;
    else if(a/c*b+d==x && a%c==0) pin=1;
    else if((a+c)/b-d==x && (a+c)%b==0) pin=1;
    else if((a-c)/b+d==x && (a-c)%b==0) pin=1;
    else if(a/c-b+d==x && a%c==0) pin=1;
    else if((a-c+b)/d==x && (a-c+b)%d==0) pin=1;
    else if((a+c-b)/d==x && (a+c-b)%d==0) pin=1;
    else if(a/c+b-d==x && a%c==0) pin=1;
    else if(a+c+d-b==x) pin=1;
    else if(a+c-d+b==x) pin=1;
    else if(a-c+d+b==x) pin=1;
    else if(a+c-d-b==x) pin=1;
    else if(a-c+d-b==x) pin=1;
    else if(a-c-d+b==x) pin=1;
    else if(a-c-d-b==x) pin=1;
    else if(a*c*d*b==x) pin=1;
    else if(a/c/d/b==x && a%c==0 && (a/c)%d==0 && (a/c/d)%b==0) pin=1;
    else if((a+c+d)*b==x) pin=1;
    else if((a+c)*d+b==x) pin=1;
    else if(a*c+d+b==x) pin=1;
    else if(a*c*d+b==x) pin=1;
    else if((a*c+d)*b==x) pin=1;
    else if((a+c)*d*b==x) pin=1;
    else if(a*c*d-b==x) pin=1;
    else if((a*c-d)*b==x) pin=1;
    else if((a-c)*d*b==x) pin=1;
    else if(a*c-d-b==x) pin=1;
    else if((a-c)*d-b==x) pin=1;
    else if((a-c-d)*b==x) pin=1;
    else if(a/c+d+b==x && a%c==0) pin=1;
    else if((a+c)/d+b==x && (a+c)%d==0) pin=1;
    else if((a+c+d)/b==x && (a+c+d)%b==0) pin=1;
    else if(a/c/d+b==x && a%c==0 && (a/c)%d==0) pin=1;
    else if((a/c+d)/b==x && a%c==0 && (a/c+d)%b==0) pin=1;
    else if((a+c)/d/b==x && (a+c)%d==0 && ((a+c)/d)%b==0) pin=1;
    else if(a/c-d-b==x && a%c==0) pin=1;
    else if((a-c)/d-b==x && (a-c)%d==0) pin=1;
    else if((a-c-d)/b==x && (a-c-d)%b==0) pin=1;
    else if(a/c/d-b==x && a%c==0 && (a/c)%d==0) pin=1;
    else if((a/c-d)/b==x && a%c==0 && (a/c-d)%b==0) pin=1;
    else if((a-c)/d/b==x && (a-c)%d==0 && ((a-c)/d)%b==0) pin=1;
    else if(a/c*d*b==x && a%c==0) pin=1;
    else if(a*c/d*b==x && (a*c)%d==0) pin=1;
    else if(a*c*d/b==x && (a*c*d)%b==0) pin=1;
    else if(a*c/d/b==x && (a*c)%d==0 && (a*c/d)%b==0) pin=1;
    else if(a/c*d/b==x && a%c==0 && (a/c*d)%b==0) pin=1;
    else if(a/c/d*b==x && a%c==0 && (a/c)%d==0) pin=1;
    else if((a+c-d)*b==x) pin=1;
    else if((a-c)*d+b==x) pin=1;
    else if(a*c-d+b==x) pin=1;
    else if((a+c)*d-b==x) pin=1;
    else if(a*c+d-b==x) pin=1;
    else if((a-c+d)*b==x) pin=1;
    else if((a-c)*d/b==x && ((a-c)*d)%b==0) pin=1;
    else if(a*c/d-b==x && (a*c)%d==0) pin=1;
    else if((a/c-d)*b==x && a%c==0) pin=1;
    else if((a-c)/d*b==x && (a-c)%d==0) pin=1;
    else if(a/c*d-b==x && a%c==0) pin=1;
    else if((a*c-d)/b==x && (a*c-d)%b==0) pin=1;
    else if(a*c/d+b==x && (a*c)%d==0) pin=1;
    else if((a/c+d)*b==x && a%c==0) pin=1;
    else if((a+c)/d*b==x && (a+c)%d==0) pin=1;
    else if((a*c+d)/b==x && (a*c+d)%b==0) pin=1;
    else if((a+c)*d/b==x && ((a+c)*d)%b==0) pin=1;
    else if(a/c*d+b==x && a%c==0) pin=1;
    else if((a+c)/d-b==x && (a+c)%d==0) pin=1;
    else if((a-c)/d+b==x && (a-c)%d==0) pin=1;
    else if(a/c-d+b==x && a%c==0) pin=1;
    else if((a-c+d)/b==x && (a-c+d)%b==0) pin=1;
    else if((a+c-d)/b==x && (a+c-d)%b==0) pin=1;
    else if(a/c+d-b==x && a%c==0) pin=1;
    else if(a+d+c-b==x) pin=1;
    else if(a+d-c+b==x) pin=1;
    else if(a-d+c+b==x) pin=1;
    else if(a+d-c-b==x) pin=1;
    else if(a-d+c-b==x) pin=1;
    else if(a-d-c+b==x) pin=1;
    else if(a-d-c-b==x) pin=1;
    else if(a*d*c*b==x) pin=1;
    else if(a/d/c/b==x && a%d==0 && (a/d)%c==0 && (a/d/c)%b==0) pin=1;
    else if((a+d+c)*b==x) pin=1;
    else if((a+d)*c+b==x) pin=1;
    else if(a*d+c+b==x) pin=1;
    else if(a*d*c+b==x) pin=1;
    else if((a*d+c)*b==x) pin=1;
    else if((a+d)*c*b==x) pin=1;
    else if(a*d*c-b==x) pin=1;
    else if((a*d-c)*b==x) pin=1;
    else if((a-d)*c*b==x) pin=1;
    else if(a*d-c-b==x) pin=1;
    else if((a-d)*c-b==x) pin=1;
    else if((a-d-c)*b==x) pin=1;
    else if(a/d+c+b==x && a%d==0) pin=1;
    else if((a+d)/c+b==x && (a+d)%c==0) pin=1;
    else if((a+d+c)/b==x && (a+d+c)%b==0) pin=1;
    else if(a/d/c+b==x && a%d==0 && (a/d)%c==0) pin=1;
    else if((a/d+c)/b==x && a%d==0 && (a/d+c)%b==0) pin=1;
    else if((a+d)/c/b==x && (a+d)%c==0 && ((a+d)/c)%b==0) pin=1;
    else if(a/d-c-b==x && a%d==0) pin=1;
    else if((a-d)/c-b==x && (a-d)%c==0) pin=1;
    else if((a-d-c)/b==x && (a-d-c)%b==0) pin=1;
    else if(a/d/c-b==x && a%d==0 && (a/d)%c==0) pin=1;
    else if((a/d-c)/b==x && a%d==0 && (a/d-c)%b==0) pin=1;
    else if((a-d)/c/b==x && (a-d)%c==0 && ((a-d)/c)%b==0) pin=1;
    else if(a/d*c*b==x && a%d==0) pin=1;
    else if(a*d/c*b==x && (a*d)%c==0) pin=1;
    else if(a*d*c/b==x && (a*d*c)%b==0) pin=1;
    else if(a*d/c/b==x && (a*d)%c==0 && (a*d/c)%b==0) pin=1;
    else if(a/d*c/b==x && a%d==0 && (a/d*c)%b==0) pin=1;
    else if(a/d/c*b==x && a%d==0 && (a/d)%c==0) pin=1;
    else if((a+d-c)*b==x) pin=1;
    else if((a-d)*c+b==x) pin=1;
    else if(a*d-c+b==x) pin=1;
    else if((a+d)*c-b==x) pin=1;
    else if(a*d+c-b==x) pin=1;
    else if((a-d+c)*b==x) pin=1;
    else if((a-d)*c/b==x && ((a-d)*c)%b==0) pin=1;
    else if(a*d/c-b==x && (a*d)%c==0) pin=1;
    else if((a/d-c)*b==x && a%d==0) pin=1;
    else if((a-d)/c*b==x && (a-d)%c==0) pin=1;
    else if(a/d*c-b==x && a%d==0) pin=1;
    else if((a*d-c)/b==x && (a*d-c)%b==0) pin=1;
    else if(a*d/c+b==x && (a*d)%c==0) pin=1;
    else if((a/d+c)*b==x && a%d==0) pin=1;
    else if((a+d)/c*b==x && (a+d)%c==0) pin=1;
    else if((a*d+c)/b==x && (a*d+c)%b==0) pin=1;
    else if((a+d)*c/b==x && ((a+d)*c)%b==0) pin=1;
    else if(a/d*c+b==x && a%d==0) pin=1;
    else if((a+d)/c-b==x && (a+d)%c==0) pin=1;
    else if((a-d)/c+b==x && (a-d)%c==0) pin=1;
    else if(a/d-c+b==x && a%d==0) pin=1;
    else if((a-d+c)/b==x && (a-d+c)%b==0) pin=1;
    else if((a+d-c)/b==x && (a+d-c)%b==0) pin=1;
    else if(a/d+c-b==x && a%d==0) pin=1;
    else if(a+d+b-c==x) pin=1;
    else if(a+d-b+c==x) pin=1;
    else if(a-d+b+c==x) pin=1;
    else if(a+d-b-c==x) pin=1;
    else if(a-d+b-c==x) pin=1;
    else if(a-d-b+c==x) pin=1;
    else if(a-d-b-c==x) pin=1;
    else if(a*d*b*c==x) pin=1;
    else if(a/d/b/c==x && a%d==0 && (a/d)%b==0 && (a/d/b)%c==0) pin=1;
    else if((a+d+b)*c==x) pin=1;
    else if((a+d)*b+c==x) pin=1;
    else if(a*d+b+c==x) pin=1;
    else if(a*d*b+c==x) pin=1;
    else if((a*d+b)*c==x) pin=1;
    else if((a+d)*b*c==x) pin=1;
    else if(a*d*b-c==x) pin=1;
    else if((a*d-b)*c==x) pin=1;
    else if((a-d)*b*c==x) pin=1;
    else if(a*d-b-c==x) pin=1;
    else if((a-d)*b-c==x) pin=1;
    else if((a-d-b)*c==x) pin=1;
    else if(a/d+b+c==x && a%d==0) pin=1;
    else if((a+d)/b+c==x && (a+d)%b==0) pin=1;
    else if((a+d+b)/c==x && (a+d+b)%c==0) pin=1;
    else if(a/d/b+c==x && a%d==0 && (a/d)%b==0) pin=1;
    else if((a/d+b)/c==x && a%d==0 && (a/d+b)%c==0) pin=1;
    else if((a+d)/b/c==x && (a+d)%b==0 && ((a+d)/b)%c==0) pin=1;
    else if(a/d-b-c==x && a%d==0) pin=1;
    else if((a-d)/b-c==x && (a-d)%b==0) pin=1;
    else if((a-d-b)/c==x && (a-d-b)%c==0) pin=1;
    else if(a/d/b-c==x && a%d==0 && (a/d)%b==0) pin=1;
    else if((a/d-b)/c==x && a%d==0 && (a/d-b)%c==0) pin=1;
    else if((a-d)/b/c==x && (a-d)%b==0 && ((a-d)/b)%c==0) pin=1;
    else if(a/d*b*c==x && a%d==0) pin=1;
    else if(a*d/b*c==x && (a*d)%b==0) pin=1;
    else if(a*d*b/c==x && (a*d*b)%c==0) pin=1;
    else if(a*d/b/c==x && (a*d)%b==0 && (a*d/b)%c==0) pin=1;
    else if(a/d*b/c==x && a%d==0 && (a/d*b)%c==0) pin=1;
    else if(a/d/b*c==x && a%d==0 && (a/d)%b==0) pin=1;
    else if((a+d-b)*c==x) pin=1;
    else if((a-d)*b+c==x) pin=1;
    else if(a*d-b+c==x) pin=1;
    else if((a+d)*b-c==x) pin=1;
    else if(a*d+b-c==x) pin=1;
    else if((a-d+b)*c==x) pin=1;
    else if((a-d)*b/c==x && ((a-d)*b)%c==0) pin=1;
    else if(a*d/b-c==x && (a*d)%b==0) pin=1;
    else if((a/d-b)*c==x && a%d==0) pin=1;
    else if((a-d)/b*c==x && (a-d)%b==0) pin=1;
    else if(a/d*b-c==x && a%d==0) pin=1;
    else if((a*d-b)/c==x && (a*d-b)%c==0) pin=1;
    else if(a*d/b+c==x && (a*d)%b==0) pin=1;
    else if((a/d+b)*c==x && a%d==0) pin=1;
    else if((a+d)/b*c==x && (a+d)%b==0) pin=1;
    else if((a*d+b)/c==x && (a*d+b)%c==0) pin=1;
    else if((a+d)*b/c==x && ((a+d)*b)%c==0) pin=1;
    else if(a/d*b+c==x && a%d==0) pin=1;
    else if((a+d)/b-c==x && (a+d)%b==0) pin=1;
    else if((a-d)/b+c==x && (a-d)%b==0) pin=1;
    else if(a/d-b+c==x && a%d==0) pin=1;
    else if((a-d+b)/c==x && (a-d+b)%c==0) pin=1;
    else if((a+d-b)/c==x && (a+d-b)%c==0) pin=1;
    else if(a/d+b-c==x && a%d==0) pin=1;
    else if(b+d+a-c==x) pin=1;
    else if(b+d-a+c==x) pin=1;
    else if(b-d+a+c==x) pin=1;
    else if(b+d-a-c==x) pin=1;
    else if(b-d+a-c==x) pin=1;
    else if(b-d-a+c==x) pin=1;
    else if(b-d-a-c==x) pin=1;
    else if(b*d*a*c==x) pin=1;
    else if(b/d/a/c==x && b%d==0 && (b/d)%a==0 && (b/d/a)%c==0) pin=1;
    else if((b+d+a)*c==x) pin=1;
    else if((b+d)*a+c==x) pin=1;
    else if(b*d+a+c==x) pin=1;
    else if(b*d*a+c==x) pin=1;
    else if((b*d+a)*c==x) pin=1;
    else if((b+d)*a*c==x) pin=1;
    else if(b*d*a-c==x) pin=1;
    else if((b*d-a)*c==x) pin=1;
    else if((b-d)*a*c==x) pin=1;
    else if(b*d-a-c==x) pin=1;
    else if((b-d)*a-c==x) pin=1;
    else if((b-d-a)*c==x) pin=1;
    else if(b/d+a+c==x && b%d==0) pin=1;
    else if((b+d)/a+c==x && (b+d)%a==0) pin=1;
    else if((b+d+a)/c==x && (b+d+a)%c==0) pin=1;
    else if(b/d/a+c==x && b%d==0 && (b/d)%a==0) pin=1;
    else if((b/d+a)/c==x && b%d==0 && (b/d+a)%c==0) pin=1;
    else if((b+d)/a/c==x && (b+d)%a==0 && ((b+d)/a)%c==0) pin=1;
    else if(b/d-a-c==x && b%d==0) pin=1;
    else if((b-d)/a-c==x && (b-d)%a==0) pin=1;
    else if((b-d-a)/c==x && (b-d-a)%c==0) pin=1;
    else if(b/d/a-c==x && b%d==0 && (b/d)%a==0) pin=1;
    else if((b/d-a)/c==x && b%d==0 && (b/d-a)%c==0) pin=1;
    else if((b-d)/a/c==x && (b-d)%a==0 && ((b-d)/a)%c==0) pin=1;
    else if(b/d*a*c==x && b%d==0) pin=1;
    else if(b*d/a*c==x && (b*d)%a==0) pin=1;
    else if(b*d*a/c==x && (b*d*a)%c==0) pin=1;
    else if(b*d/a/c==x && (b*d)%a==0 && (b*d/a)%c==0) pin=1;
    else if(b/d*a/c==x && b%d==0 && (b/d*a)%c==0) pin=1;
    else if(b/d/a*c==x && b%d==0 && (b/d)%a==0) pin=1;
    else if((b+d-a)*c==x) pin=1;
    else if((b-d)*a+c==x) pin=1;
    else if(b*d-a+c==x) pin=1;
    else if((b+d)*a-c==x) pin=1;
    else if(b*d+a-c==x) pin=1;
    else if((b-d+a)*c==x) pin=1;
    else if((b-d)*a/c==x && ((b-d)*a)%c==0) pin=1;
    else if(b*d/a-c==x && (b*d)%a==0) pin=1;
    else if((b/d-a)*c==x && b%d==0) pin=1;
    else if((b-d)/a*c==x && (b-d)%a==0) pin=1;
    else if(b/d*a-c==x && b%d==0) pin=1;
    else if((b*d-a)/c==x && (b*d-a)%c==0) pin=1;
    else if(b*d/a+c==x && (b*d)%a==0) pin=1;
    else if((b/d+a)*c==x && b%d==0) pin=1;
    else if((b+d)/a*c==x && (b+d)%a==0) pin=1;
    else if((b*d+a)/c==x && (b*d+a)%c==0) pin=1;
    else if((b+d)*a/c==x && ((b+d)*a)%c==0) pin=1;
    else if(b/d*a+c==x && b%d==0) pin=1;
    else if((b+d)/a-c==x && (b+d)%a==0) pin=1;
    else if((b-d)/a+c==x && (b-d)%a==0) pin=1;
    else if(b/d-a+c==x && b%d==0) pin=1;
    else if((b-d+a)/c==x && (b-d+a)%c==0) pin=1;
    else if((b+d-a)/c==x && (b+d-a)%c==0) pin=1;
    else if(b/d+a-c==x && b%d==0) pin=1;
    else if(b+a+c-d==x) pin=1;
    else if(b+a-c+d==x) pin=1;
    else if(b-a+c+d==x) pin=1;
    else if(b+a-c-d==x) pin=1;
    else if(b-a+c-d==x) pin=1;
    else if(b-a-c+d==x) pin=1;
    else if(b-a-c-d==x) pin=1;
    else if(b*a*c*d==x) pin=1;
    else if(b/a/c/d==x && b%a==0 && (b/a)%c==0 && (b/a/c)%d==0) pin=1;
    else if((b+a+c)*d==x) pin=1;
    else if((b+a)*c+d==x) pin=1;
    else if(b*a+c+d==x) pin=1;
    else if(b*a*c+d==x) pin=1;
    else if((b*a+c)*d==x) pin=1;
    else if((b+a)*c*d==x) pin=1;
    else if(b*a*c-d==x) pin=1;
    else if((b*a-c)*d==x) pin=1;
    else if((b-a)*c*d==x) pin=1;
    else if(b*a-c-d==x) pin=1;
    else if((b-a)*c-d==x) pin=1;
    else if((b-a-c)*d==x) pin=1;
    else if(b/a+c+d==x && b%a==0) pin=1;
    else if((b+a)/c+d==x && (b+a)%c==0) pin=1;
    else if((b+a+c)/d==x && (b+a+c)%d==0) pin=1;
    else if(b/a/c+d==x && b%a==0 && (b/a)%c==0) pin=1;
    else if((b/a+c)/d==x && b%a==0 && (b/a+c)%d==0) pin=1;
    else if((b+a)/c/d==x && (b+a)%c==0 && ((b+a)/c)%d==0) pin=1;
    else if(b/a-c-d==x && b%a==0) pin=1;
    else if((b-a)/c-d==x && (b-a)%c==0) pin=1;
    else if((b-a-c)/d==x && (b-a-c)%d==0) pin=1;
    else if(b/a/c-d==x && b%a==0 && (b/a)%c==0) pin=1;
    else if((b/a-c)/d==x && b%a==0 && (b/a-c)%d==0) pin=1;
    else if((b-a)/c/d==x && (b-a)%c==0 && ((b-a)/c)%d==0) pin=1;
    else if(b/a*c*d==x && b%a==0) pin=1;
    else if(b*a/c*d==x && (b*a)%c==0) pin=1;
    else if(b*a*c/d==x && (b*a*c)%d==0) pin=1;
    else if(b*a/c/d==x && (b*a)%c==0 && (b*a/c)%d==0) pin=1;
    else if(b/a*c/d==x && b%a==0 && (b/a*c)%d==0) pin=1;
    else if(b/a/c*d==x && b%a==0 && (b/a)%c==0) pin=1;
    else if((b+a-c)*d==x) pin=1;
    else if((b-a)*c+d==x) pin=1;
    else if(b*a-c+d==x) pin=1;
    else if((b+a)*c-d==x) pin=1;
    else if(b*a+c-d==x) pin=1;
    else if((b-a+c)*d==x) pin=1;
    else if((b-a)*c/d==x && ((b-a)*c)%d==0) pin=1;
    else if(b*a/c-d==x && (b*a)%c==0) pin=1;
    else if((b/a-c)*d==x && b%a==0) pin=1;
    else if((b-a)/c*d==x && (b-a)%c==0) pin=1;
    else if(b/a*c-d==x && b%a==0) pin=1;
    else if((b*a-c)/d==x && (b*a-c)%d==0) pin=1;
    else if(b*a/c+d==x && (b*a)%c==0) pin=1;
    else if((b/a+c)*d==x && b%a==0) pin=1;
    else if((b+a)/c*d==x && (b+a)%c==0) pin=1;
    else if((b*a+c)/d==x && (b*a+c)%d==0) pin=1;
    else if((b+a)*c/d==x && ((b+a)*c)%d==0) pin=1;
    else if(b/a*c+d==x && b%a==0) pin=1;
    else if((b+a)/c-d==x && (b+a)%c==0) pin=1;
    else if((b-a)/c+d==x && (b-a)%c==0) pin=1;
    else if(b/a-c+d==x && b%a==0) pin=1;
    else if((b-a+c)/d==x && (b-a+c)%d==0) pin=1;
    else if((b+a-c)/d==x && (b+a-c)%d==0) pin=1;
    else if(b/a+c-d==x && b%a==0) pin=1;
    else if(b+c+a-d==x) pin=1;
    else if(b+c-a+d==x) pin=1;
    else if(b-c+a+d==x) pin=1;
    else if(b+c-a-d==x) pin=1;
    else if(b-c+a-d==x) pin=1;
    else if(b-c-a+d==x) pin=1;
    else if(b-c-a-d==x) pin=1;
    else if(b*c*a*d==x) pin=1;
    else if(b/c/a/d==x && b%c==0 && (b/c)%a==0 && (b/c/a)%d==0) pin=1;
    else if((b+c+a)*d==x) pin=1;
    else if((b+c)*a+d==x) pin=1;
    else if(b*c+a+d==x) pin=1;
    else if(b*c*a+d==x) pin=1;
    else if((b*c+a)*d==x) pin=1;
    else if((b+c)*a*d==x) pin=1;
    else if(b*c*a-d==x) pin=1;
    else if((b*c-a)*d==x) pin=1;
    else if((b-c)*a*d==x) pin=1;
    else if(b*c-a-d==x) pin=1;
    else if((b-c)*a-d==x) pin=1;
    else if((b-c-a)*d==x) pin=1;
    else if(b/c+a+d==x && b%c==0) pin=1;
    else if((b+c)/a+d==x && (b+c)%a==0) pin=1;
    else if((b+c+a)/d==x && (b+c+a)%d==0) pin=1;
    else if(b/c/a+d==x && b%c==0 && (b/c)%a==0) pin=1;
    else if((b/c+a)/d==x && b%c==0 && (b/c+a)%d==0) pin=1;
    else if((b+c)/a/d==x && (b+c)%a==0 && ((b+c)/a)%d==0) pin=1;
    else if(b/c-a-d==x && b%c==0) pin=1;
    else if((b-c)/a-d==x && (b-c)%a==0) pin=1;
    else if((b-c-a)/d==x && (b-c-a)%d==0) pin=1;
    else if(b/c/a-d==x && b%c==0 && (b/c)%a==0) pin=1;
    else if((b/c-a)/d==x && b%c==0 && (b/c-a)%d==0) pin=1;
    else if((b-c)/a/d==x && (b-c)%a==0 && ((b-c)/a)%d==0) pin=1;
    else if(b/c*a*d==x && b%c==0) pin=1;
    else if(b*c/a*d==x && (b*c)%a==0) pin=1;
    else if(b*c*a/d==x && (b*c*a)%d==0) pin=1;
    else if(b*c/a/d==x && (b*c)%a==0 && (b*c/a)%d==0) pin=1;
    else if(b/c*a/d==x && b%c==0 && (b/c*a)%d==0) pin=1;
    else if(b/c/a*d==x && b%c==0 && (b/c)%a==0) pin=1;
    else if((b+c-a)*d==x) pin=1;
    else if((b-c)*a+d==x) pin=1;
    else if(b*c-a+d==x) pin=1;
    else if((b+c)*a-d==x) pin=1;
    else if(b*c+a-d==x) pin=1;
    else if((b-c+a)*d==x) pin=1;
    else if((b-c)*a/d==x && ((b-c)*a)%d==0) pin=1;
    else if(b*c/a-d==x && (b*c)%a==0) pin=1;
    else if((b/c-a)*d==x && b%c==0) pin=1;
    else if((b-c)/a*d==x && (b-c)%a==0) pin=1;
    else if(b/c*a-d==x && b%c==0) pin=1;
    else if((b*c-a)/d==x && (b*c-a)%d==0) pin=1;
    else if(b*c/a+d==x && (b*c)%a==0) pin=1;
    else if((b/c+a)*d==x && b%c==0) pin=1;
    else if((b+c)/a*d==x && (b+c)%a==0) pin=1;
    else if((b*c+a)/d==x && (b*c+a)%d==0) pin=1;
    else if((b+c)*a/d==x && ((b+c)*a)%d==0) pin=1;
    else if(b/c*a+d==x && b%c==0) pin=1;
    else if((b+c)/a-d==x && (b+c)%a==0) pin=1;
    else if((b-c)/a+d==x && (b-c)%a==0) pin=1;
    else if(b/c-a+d==x && b%c==0) pin=1;
    else if((b-c+a)/d==x && (b-c+a)%d==0) pin=1;
    else if((b+c-a)/d==x && (b+c-a)%d==0) pin=1;
    else if(b/c+a-d==x && b%c==0) pin=1;
    else if(b+c+d-a==x) pin=1;
    else if(b+c-d+a==x) pin=1;
    else if(b-c+d+a==x) pin=1;
    else if(b+c-d-a==x) pin=1;
    else if(b-c+d-a==x) pin=1;
    else if(b-c-d+a==x) pin=1;
    else if(b-c-d-a==x) pin=1;
    else if(b*c*d*a==x) pin=1;
    else if(b/c/d/a==x && b%c==0 && (b/c)%d==0 && (b/c/d)%a==0) pin=1;
    else if((b+c+d)*a==x) pin=1;
    else if((b+c)*d+a==x) pin=1;
    else if(b*c+d+a==x) pin=1;
    else if(b*c*d+a==x) pin=1;
    else if((b*c+d)*a==x) pin=1;
    else if((b+c)*d*a==x) pin=1;
    else if(b*c*d-a==x) pin=1;
    else if((b*c-d)*a==x) pin=1;
    else if((b-c)*d*a==x) pin=1;
    else if(b*c-d-a==x) pin=1;
    else if((b-c)*d-a==x) pin=1;
    else if((b-c-d)*a==x) pin=1;
    else if(b/c+d+a==x && b%c==0) pin=1;
    else if((b+c)/d+a==x && (b+c)%d==0) pin=1;
    else if((b+c+d)/a==x && (b+c+d)%a==0) pin=1;
    else if(b/c/d+a==x && b%c==0 && (b/c)%d==0) pin=1;
    else if((b/c+d)/a==x && b%c==0 && (b/c+d)%a==0) pin=1;
    else if((b+c)/d/a==x && (b+c)%d==0 && ((b+c)/d)%a==0) pin=1;
    else if(b/c-d-a==x && b%c==0) pin=1;
    else if((b-c)/d-a==x && (b-c)%d==0) pin=1;
    else if((b-c-d)/a==x && (b-c-d)%a==0) pin=1;
    else if(b/c/d-a==x && b%c==0 && (b/c)%d==0) pin=1;
    else if((b/c-d)/a==x && b%c==0 && (b/c-d)%a==0) pin=1;
    else if((b-c)/d/a==x && (b-c)%d==0 && ((b-c)/d)%a==0) pin=1;
    else if(b/c*d*a==x && b%c==0) pin=1;
    else if(b*c/d*a==x && (b*c)%d==0) pin=1;
    else if(b*c*d/a==x && (b*c*d)%a==0) pin=1;
    else if(b*c/d/a==x && (b*c)%d==0 && (b*c/d)%a==0) pin=1;
    else if(b/c*d/a==x && b%c==0 && (b/c*d)%a==0) pin=1;
    else if(b/c/d*a==x && b%c==0 && (b/c)%d==0) pin=1;
    else if((b+c-d)*a==x) pin=1;
    else if((b-c)*d+a==x) pin=1;
    else if(b*c-d+a==x) pin=1;
    else if((b+c)*d-a==x) pin=1;
    else if(b*c+d-a==x) pin=1;
    else if((b-c+d)*a==x) pin=1;
    else if((b-c)*d/a==x && ((b-c)*d)%a==0) pin=1;
    else if(b*c/d-a==x && (b*c)%d==0) pin=1;
    else if((b/c-d)*a==x && b%c==0) pin=1;
    else if((b-c)/d*a==x && (b-c)%d==0) pin=1;
    else if(b/c*d-a==x && b%c==0) pin=1;
    else if((b*c-d)/a==x && (b*c-d)%a==0) pin=1;
    else if(b*c/d+a==x && (b*c)%d==0) pin=1;
    else if((b/c+d)*a==x && b%c==0) pin=1;
    else if((b+c)/d*a==x && (b+c)%d==0) pin=1;
    else if((b*c+d)/a==x && (b*c+d)%a==0) pin=1;
    else if((b+c)*d/a==x && ((b+c)*d)%a==0) pin=1;
    else if(b/c*d+a==x && b%c==0) pin=1;
    else if((b+c)/d-a==x && (b+c)%d==0) pin=1;
    else if((b-c)/d+a==x && (b-c)%d==0) pin=1;
    else if(b/c-d+a==x && b%c==0) pin=1;
    else if((b-c+d)/a==x && (b-c+d)%a==0) pin=1;
    else if((b+c-d)/a==x && (b+c-d)%a==0) pin=1;
    else if(b/c+d-a==x && b%c==0) pin=1;
    else if(b+d+c-a==x) pin=1;
    else if(b+d-c+a==x) pin=1;
    else if(b-d+c+a==x) pin=1;
    else if(b+d-c-a==x) pin=1;
    else if(b-d+c-a==x) pin=1;
    else if(b-d-c+a==x) pin=1;
    else if(b-d-c-a==x) pin=1;
    else if(b*d*c*a==x) pin=1;
    else if(b/d/c/a==x && b%d==0 && (b/d)%c==0 && (b/d/c)%a==0) pin=1;
    else if((b+d+c)*a==x) pin=1;
    else if((b+d)*c+a==x) pin=1;
    else if(b*d+c+a==x) pin=1;
    else if(b*d*c+a==x) pin=1;
    else if((b*d+c)*a==x) pin=1;
    else if((b+d)*c*a==x) pin=1;
    else if(b*d*c-a==x) pin=1;
    else if((b*d-c)*a==x) pin=1;
    else if((b-d)*c*a==x) pin=1;
    else if(b*d-c-a==x) pin=1;
    else if((b-d)*c-a==x) pin=1;
    else if((b-d-c)*a==x) pin=1;
    else if(b/d+c+a==x && b%d==0) pin=1;
    else if((b+d)/c+a==x && (b+d)%c==0) pin=1;
    else if((b+d+c)/a==x && (b+d+c)%a==0) pin=1;
    else if(b/d/c+a==x && b%d==0 && (b/d)%c==0) pin=1;
    else if((b/d+c)/a==x && b%d==0 && (b/d+c)%a==0) pin=1;
    else if((b+d)/c/a==x && (b+d)%c==0 && ((b+d)/c)%a==0) pin=1;
    else if(b/d-c-a==x && b%d==0) pin=1;
    else if((b-d)/c-a==x && (b-d)%c==0) pin=1;
    else if((b-d-c)/a==x && (b-d-c)%a==0) pin=1;
    else if(b/d/c-a==x && b%d==0 && (b/d)%c==0) pin=1;
    else if((b/d-c)/a==x && b%d==0 && (b/d-c)%a==0) pin=1;
    else if((b-d)/c/a==x && (b-d)%c==0 && ((b-d)/c)%a==0) pin=1;
    else if(b/d*c*a==x && b%d==0) pin=1;
    else if(b*d/c*a==x && (b*d)%c==0) pin=1;
    else if(b*d*c/a==x && (b*d*c)%a==0) pin=1;
    else if(b*d/c/a==x && (b*d)%c==0 && (b*d/c)%a==0) pin=1;
    else if(b/d*c/a==x && b%d==0 && (b/d*c)%a==0) pin=1;
    else if(b/d/c*a==x && b%d==0 && (b/d)%c==0) pin=1;
    else if((b+d-c)*a==x) pin=1;
    else if((b-d)*c+a==x) pin=1;
    else if(b*d-c+a==x) pin=1;
    else if((b+d)*c-a==x) pin=1;
    else if(b*d+c-a==x) pin=1;
    else if((b-d+c)*a==x) pin=1;
    else if((b-d)*c/a==x && ((b-d)*c)%a==0) pin=1;
    else if(b*d/c-a==x && (b*d)%c==0) pin=1;
    else if((b/d-c)*a==x && b%d==0) pin=1;
    else if((b-d)/c*a==x && (b-d)%c==0) pin=1;
    else if(b/d*c-a==x && b%d==0) pin=1;
    else if((b*d-c)/a==x && (b*d-c)%a==0) pin=1;
    else if(b*d/c+a==x && (b*d)%c==0) pin=1;
    else if((b/d+c)*a==x && b%d==0) pin=1;
    else if((b+d)/c*a==x && (b+d)%c==0) pin=1;
    else if((b*d+c)/a==x && (b*d+c)%a==0) pin=1;
    else if((b+d)*c/a==x && ((b+d)*c)%a==0) pin=1;
    else if(b/d*c+a==x && b%d==0) pin=1;
    else if((b+d)/c-a==x && (b+d)%c==0) pin=1;
    else if((b-d)/c+a==x && (b-d)%c==0) pin=1;
    else if(b/d-c+a==x && b%d==0) pin=1;
    else if((b-d+c)/a==x && (b-d+c)%a==0) pin=1;
    else if((b+d-c)/a==x && (b+d-c)%a==0) pin=1;
    else if(b/d+c-a==x && b%d==0) pin=1;
    else if(b+a+d-c==x) pin=1;
    else if(b+a-d+c==x) pin=1;
    else if(b-a+d+c==x) pin=1;
    else if(b+a-d-c==x) pin=1;
    else if(b-a+d-c==x) pin=1;
    else if(b-a-d+c==x) pin=1;
    else if(b-a-d-c==x) pin=1;
    else if(b*a*d*c==x) pin=1;
    else if(b/a/d/c==x && b%a==0 && (b/a)%d==0 && (b/a/d)%c==0) pin=1;
    else if((b+a+d)*c==x) pin=1;
    else if((b+a)*d+c==x) pin=1;
    else if(b*a+d+c==x) pin=1;
    else if(b*a*d+c==x) pin=1;
    else if((b*a+d)*c==x) pin=1;
    else if((b+a)*d*c==x) pin=1;
    else if(b*a*d-c==x) pin=1;
    else if((b*a-d)*c==x) pin=1;
    else if((b-a)*d*c==x) pin=1;
    else if(b*a-d-c==x) pin=1;
    else if((b-a)*d-c==x) pin=1;
    else if((b-a-d)*c==x) pin=1;
    else if(b/a+d+c==x && b%a==0) pin=1;
    else if((b+a)/d+c==x && (b+a)%d==0) pin=1;
    else if((b+a+d)/c==x && (b+a+d)%c==0) pin=1;
    else if(b/a/d+c==x && b%a==0 && (b/a)%d==0) pin=1;
    else if((b/a+d)/c==x && b%a==0 && (b/a+d)%c==0) pin=1;
    else if((b+a)/d/c==x && (b+a)%d==0 && ((b+a)/d)%c==0) pin=1;
    else if(b/a-d-c==x && b%a==0) pin=1;
    else if((b-a)/d-c==x && (b-a)%d==0) pin=1;
    else if((b-a-d)/c==x && (b-a-d)%c==0) pin=1;
    else if(b/a/d-c==x && b%a==0 && (b/a)%d==0) pin=1;
    else if((b/a-d)/c==x && b%a==0 && (b/a-d)%c==0) pin=1;
    else if((b-a)/d/c==x && (b-a)%d==0 && ((b-a)/d)%c==0) pin=1;
    else if(b/a*d*c==x && b%a==0) pin=1;
    else if(b*a/d*c==x && (b*a)%d==0) pin=1;
    else if(b*a*d/c==x && (b*a*d)%c==0) pin=1;
    else if(b*a/d/c==x && (b*a)%d==0 && (b*a/d)%c==0) pin=1;
    else if(b/a*d/c==x && b%a==0 && (b/a*d)%c==0) pin=1;
    else if(b/a/d*c==x && b%a==0 && (b/a)%d==0) pin=1;
    else if((b+a-d)*c==x) pin=1;
    else if((b-a)*d+c==x) pin=1;
    else if(b*a-d+c==x) pin=1;
    else if((b+a)*d-c==x) pin=1;
    else if(b*a+d-c==x) pin=1;
    else if((b-a+d)*c==x) pin=1;
    else if((b-a)*d/c==x && ((b-a)*d)%c==0) pin=1;
    else if(b*a/d-c==x && (b*a)%d==0) pin=1;
    else if((b/a-d)*c==x && b%a==0) pin=1;
    else if((b-a)/d*c==x && (b-a)%d==0) pin=1;
    else if(b/a*d-c==x && b%a==0) pin=1;
    else if((b*a-d)/c==x && (b*a-d)%c==0) pin=1;
    else if(b*a/d+c==x && (b*a)%d==0) pin=1;
    else if((b/a+d)*c==x && b%a==0) pin=1;
    else if((b+a)/d*c==x && (b+a)%d==0) pin=1;
    else if((b*a+d)/c==x && (b*a+d)%c==0) pin=1;
    else if((b+a)*d/c==x && ((b+a)*d)%c==0) pin=1;
    else if(b/a*d+c==x && b%a==0) pin=1;
    else if((b+a)/d-c==x && (b+a)%d==0) pin=1;
    else if((b-a)/d+c==x && (b-a)%d==0) pin=1;
    else if(b/a-d+c==x && b%a==0) pin=1;
    else if((b-a+d)/c==x && (b-a+d)%c==0) pin=1;
    else if((b+a-d)/c==x && (b+a-d)%c==0) pin=1;
    else if(b/a+d-c==x && b%a==0) pin=1;
    else if(c+b+a-d==x) pin=1;
    else if(c+b-a+d==x) pin=1;
    else if(c-b+a+d==x) pin=1;
    else if(c+b-a-d==x) pin=1;
    else if(c-b+a-d==x) pin=1;
    else if(c-b-a+d==x) pin=1;
    else if(c-b-a-d==x) pin=1;
    else if(c*b*a*d==x) pin=1;
    else if(c/b/a/d==x && c%b==0 && (c/b)%a==0 && (c/b/a)%d==0) pin=1;
    else if((c+b+a)*d==x) pin=1;
    else if((c+b)*a+d==x) pin=1;
    else if(c*b+a+d==x) pin=1;
    else if(c*b*a+d==x) pin=1;
    else if((c*b+a)*d==x) pin=1;
    else if((c+b)*a*d==x) pin=1;
    else if(c*b*a-d==x) pin=1;
    else if((c*b-a)*d==x) pin=1;
    else if((c-b)*a*d==x) pin=1;
    else if(c*b-a-d==x) pin=1;
    else if((c-b)*a-d==x) pin=1;
    else if((c-b-a)*d==x) pin=1;
    else if(c/b+a+d==x && c%b==0) pin=1;
    else if((c+b)/a+d==x && (c+b)%a==0) pin=1;
    else if((c+b+a)/d==x && (c+b+a)%d==0) pin=1;
    else if(c/b/a+d==x && c%b==0 && (c/b)%a==0) pin=1;
    else if((c/b+a)/d==x && c%b==0 && (c/b+a)%d==0) pin=1;
    else if((c+b)/a/d==x && (c+b)%a==0 && ((c+b)/a)%d==0) pin=1;
    else if(c/b-a-d==x && c%b==0) pin=1;
    else if((c-b)/a-d==x && (c-b)%a==0) pin=1;
    else if((c-b-a)/d==x && (c-b-a)%d==0) pin=1;
    else if(c/b/a-d==x && c%b==0 && (c/b)%a==0) pin=1;
    else if((c/b-a)/d==x && c%b==0 && (c/b-a)%d==0) pin=1;
    else if((c-b)/a/d==x && (c-b)%a==0 && ((c-b)/a)%d==0) pin=1;
    else if(c/b*a*d==x && c%b==0) pin=1;
    else if(c*b/a*d==x && (c*b)%a==0) pin=1;
    else if(c*b*a/d==x && (c*b*a)%d==0) pin=1;
    else if(c*b/a/d==x && (c*b)%a==0 && (c*b/a)%d==0) pin=1;
    else if(c/b*a/d==x && c%b==0 && (c/b*a)%d==0) pin=1;
    else if(c/b/a*d==x && c%b==0 && (c/b)%a==0) pin=1;
    else if((c+b-a)*d==x) pin=1;
    else if((c-b)*a+d==x) pin=1;
    else if(c*b-a+d==x) pin=1;
    else if((c+b)*a-d==x) pin=1;
    else if(c*b+a-d==x) pin=1;
    else if((c-b+a)*d==x) pin=1;
    else if((c-b)*a/d==x && ((c-b)*a)%d==0) pin=1;
    else if(c*b/a-d==x && (c*b)%a==0) pin=1;
    else if((c/b-a)*d==x && c%b==0) pin=1;
    else if((c-b)/a*d==x && (c-b)%a==0) pin=1;
    else if(c/b*a-d==x && c%b==0) pin=1;
    else if((c*b-a)/d==x && (c*b-a)%d==0) pin=1;
    else if(c*b/a+d==x && (c*b)%a==0) pin=1;
    else if((c/b+a)*d==x && c%b==0) pin=1;
    else if((c+b)/a*d==x && (c+b)%a==0) pin=1;
    else if((c*b+a)/d==x && (c*b+a)%d==0) pin=1;
    else if((c+b)*a/d==x && ((c+b)*a)%d==0) pin=1;
    else if(c/b*a+d==x && c%b==0) pin=1;
    else if((c+b)/a-d==x && (c+b)%a==0) pin=1;
    else if((c-b)/a+d==x && (c-b)%a==0) pin=1;
    else if(c/b-a+d==x && c%b==0) pin=1;
    else if((c-b+a)/d==x && (c-b+a)%d==0) pin=1;
    else if((c+b-a)/d==x && (c+b-a)%d==0) pin=1;
    else if(c/b+a-d==x && c%b==0) pin=1;
    else if(c+b+d-a==x) pin=1;
    else if(c+b-d+a==x) pin=1;
    else if(c-b+d+a==x) pin=1;
    else if(c+b-d-a==x) pin=1;
    else if(c-b+d-a==x) pin=1;
    else if(c-b-d+a==x) pin=1;
    else if(c-b-d-a==x) pin=1;
    else if(c*b*d*a==x) pin=1;
    else if(c/b/d/a==x && c%b==0 && (c/b)%d==0 && (c/b/d)%a==0) pin=1;
    else if((c+b+d)*a==x) pin=1;
    else if((c+b)*d+a==x) pin=1;
    else if(c*b+d+a==x) pin=1;
    else if(c*b*d+a==x) pin=1;
    else if((c*b+d)*a==x) pin=1;
    else if((c+b)*d*a==x) pin=1;
    else if(c*b*d-a==x) pin=1;
    else if((c*b-d)*a==x) pin=1;
    else if((c-b)*d*a==x) pin=1;
    else if(c*b-d-a==x) pin=1;
    else if((c-b)*d-a==x) pin=1;
    else if((c-b-d)*a==x) pin=1;
    else if(c/b+d+a==x && c%b==0) pin=1;
    else if((c+b)/d+a==x && (c+b)%d==0) pin=1;
    else if((c+b+d)/a==x && (c+b+d)%a==0) pin=1;
    else if(c/b/d+a==x && c%b==0 && (c/b)%d==0) pin=1;
    else if((c/b+d)/a==x && c%b==0 && (c/b+d)%a==0) pin=1;
    else if((c+b)/d/a==x && (c+b)%d==0 && ((c+b)/d)%a==0) pin=1;
    else if(c/b-d-a==x && c%b==0) pin=1;
    else if((c-b)/d-a==x && (c-b)%d==0) pin=1;
    else if((c-b-d)/a==x && (c-b-d)%a==0) pin=1;
    else if(c/b/d-a==x && c%b==0 && (c/b)%d==0) pin=1;
    else if((c/b-d)/a==x && c%b==0 && (c/b-d)%a==0) pin=1;
    else if((c-b)/d/a==x && (c-b)%d==0 && ((c-b)/d)%a==0) pin=1;
    else if(c/b*d*a==x && c%b==0) pin=1;
    else if(c*b/d*a==x && (c*b)%d==0) pin=1;
    else if(c*b*d/a==x && (c*b*d)%a==0) pin=1;
    else if(c*b/d/a==x && (c*b)%d==0 && (c*b/d)%a==0) pin=1;
    else if(c/b*d/a==x && c%b==0 && (c/b*d)%a==0) pin=1;
    else if(c/b/d*a==x && c%b==0 && (c/b)%d==0) pin=1;
    else if((c+b-d)*a==x) pin=1;
    else if((c-b)*d+a==x) pin=1;
    else if(c*b-d+a==x) pin=1;
    else if((c+b)*d-a==x) pin=1;
    else if(c*b+d-a==x) pin=1;
    else if((c-b+d)*a==x) pin=1;
    else if((c-b)*d/a==x && ((c-b)*d)%a==0) pin=1;
    else if(c*b/d-a==x && (c*b)%d==0) pin=1;
    else if((c/b-d)*a==x && c%b==0) pin=1;
    else if((c-b)/d*a==x && (c-b)%d==0) pin=1;
    else if(c/b*d-a==x && c%b==0) pin=1;
    else if((c*b-d)/a==x && (c*b-d)%a==0) pin=1;
    else if(c*b/d+a==x && (c*b)%d==0) pin=1;
    else if((c/b+d)*a==x && c%b==0) pin=1;
    else if((c+b)/d*a==x && (c+b)%d==0) pin=1;
    else if((c*b+d)/a==x && (c*b+d)%a==0) pin=1;
    else if((c+b)*d/a==x && ((c+b)*d)%a==0) pin=1;
    else if(c/b*d+a==x && c%b==0) pin=1;
    else if((c+b)/d-a==x && (c+b)%d==0) pin=1;
    else if((c-b)/d+a==x && (c-b)%d==0) pin=1;
    else if(c/b-d+a==x && c%b==0) pin=1;
    else if((c-b+d)/a==x && (c-b+d)%a==0) pin=1;
    else if((c+b-d)/a==x && (c+b-d)%a==0) pin=1;
    else if(c/b+d-a==x && c%b==0) pin=1;
    else if(c+a+d-b==x) pin=1;
    else if(c+a-d+b==x) pin=1;
    else if(c-a+d+b==x) pin=1;
    else if(c+a-d-b==x) pin=1;
    else if(c-a+d-b==x) pin=1;
    else if(c-a-d+b==x) pin=1;
    else if(c-a-d-b==x) pin=1;
    else if(c*a*d*b==x) pin=1;
    else if(c/a/d/b==x && c%a==0 && (c/a)%d==0 && (c/a/d)%b==0) pin=1;
    else if((c+a+d)*b==x) pin=1;
    else if((c+a)*d+b==x) pin=1;
    else if(c*a+d+b==x) pin=1;
    else if(c*a*d+b==x) pin=1;
    else if((c*a+d)*b==x) pin=1;
    else if((c+a)*d*b==x) pin=1;
    else if(c*a*d-b==x) pin=1;
    else if((c*a-d)*b==x) pin=1;
    else if((c-a)*d*b==x) pin=1;
    else if(c*a-d-b==x) pin=1;
    else if((c-a)*d-b==x) pin=1;
    else if((c-a-d)*b==x) pin=1;
    else if(c/a+d+b==x && c%a==0) pin=1;
    else if((c+a)/d+b==x && (c+a)%d==0) pin=1;
    else if((c+a+d)/b==x && (c+a+d)%b==0) pin=1;
    else if(c/a/d+b==x && c%a==0 && (c/a)%d==0) pin=1;
    else if((c/a+d)/b==x && c%a==0 && (c/a+d)%b==0) pin=1;
    else if((c+a)/d/b==x && (c+a)%d==0 && ((c+a)/d)%b==0) pin=1;
    else if(c/a-d-b==x && c%a==0) pin=1;
    else if((c-a)/d-b==x && (c-a)%d==0) pin=1;
    else if((c-a-d)/b==x && (c-a-d)%b==0) pin=1;
    else if(c/a/d-b==x && c%a==0 && (c/a)%d==0) pin=1;
    else if((c/a-d)/b==x && c%a==0 && (c/a-d)%b==0) pin=1;
    else if((c-a)/d/b==x && (c-a)%d==0 && ((c-a)/d)%b==0) pin=1;
    else if(c/a*d*b==x && c%a==0) pin=1;
    else if(c*a/d*b==x && (c*a)%d==0) pin=1;
    else if(c*a*d/b==x && (c*a*d)%b==0) pin=1;
    else if(c*a/d/b==x && (c*a)%d==0 && (c*a/d)%b==0) pin=1;
    else if(c/a*d/b==x && c%a==0 && (c/a*d)%b==0) pin=1;
    else if(c/a/d*b==x && c%a==0 && (c/a)%d==0) pin=1;
    else if((c+a-d)*b==x) pin=1;
    else if((c-a)*d+b==x) pin=1;
    else if(c*a-d+b==x) pin=1;
    else if((c+a)*d-b==x) pin=1;
    else if(c*a+d-b==x) pin=1;
    else if((c-a+d)*b==x) pin=1;
    else if((c-a)*d/b==x && ((c-a)*d)%b==0) pin=1;
    else if(c*a/d-b==x && (c*a)%d==0) pin=1;
    else if((c/a-d)*b==x && c%a==0) pin=1;
    else if((c-a)/d*b==x && (c-a)%d==0) pin=1;
    else if(c/a*d-b==x && c%a==0) pin=1;
    else if((c*a-d)/b==x && (c*a-d)%b==0) pin=1;
    else if(c*a/d+b==x && (c*a)%d==0) pin=1;
    else if((c/a+d)*b==x && c%a==0) pin=1;
    else if((c+a)/d*b==x && (c+a)%d==0) pin=1;
    else if((c*a+d)/b==x && (c*a+d)%b==0) pin=1;
    else if((c+a)*d/b==x && ((c+a)*d)%b==0) pin=1;
    else if(c/a*d+b==x && c%a==0) pin=1;
    else if((c+a)/d-b==x && (c+a)%d==0) pin=1;
    else if((c-a)/d+b==x && (c-a)%d==0) pin=1;
    else if(c/a-d+b==x && c%a==0) pin=1;
    else if((c-a+d)/b==x && (c-a+d)%b==0) pin=1;
    else if((c+a-d)/b==x && (c+a-d)%b==0) pin=1;
    else if(c/a+d-b==x && c%a==0) pin=1;
    else if(c+a+b-d==x) pin=1;
    else if(c+a-b+d==x) pin=1;
    else if(c-a+b+d==x) pin=1;
    else if(c+a-b-d==x) pin=1;
    else if(c-a+b-d==x) pin=1;
    else if(c-a-b+d==x) pin=1;
    else if(c-a-b-d==x) pin=1;
    else if(c*a*b*d==x) pin=1;
    else if(c/a/b/d==x && c%a==0 && (c/a)%b==0 && (c/a/b)%d==0) pin=1;
    else if((c+a+b)*d==x) pin=1;
    else if((c+a)*b+d==x) pin=1;
    else if(c*a+b+d==x) pin=1;
    else if(c*a*b+d==x) pin=1;
    else if((c*a+b)*d==x) pin=1;
    else if((c+a)*b*d==x) pin=1;
    else if(c*a*b-d==x) pin=1;
    else if((c*a-b)*d==x) pin=1;
    else if((c-a)*b*d==x) pin=1;
    else if(c*a-b-d==x) pin=1;
    else if((c-a)*b-d==x) pin=1;
    else if((c-a-b)*d==x) pin=1;
    else if(c/a+b+d==x && c%a==0) pin=1;
    else if((c+a)/b+d==x && (c+a)%b==0) pin=1;
    else if((c+a+b)/d==x && (c+a+b)%d==0) pin=1;
    else if(c/a/b+d==x && c%a==0 && (c/a)%b==0) pin=1;
    else if((c/a+b)/d==x && c%a==0 && (c/a+b)%d==0) pin=1;
    else if((c+a)/b/d==x && (c+a)%b==0 && ((c+a)/b)%d==0) pin=1;
    else if(c/a-b-d==x && c%a==0) pin=1;
    else if((c-a)/b-d==x && (c-a)%b==0) pin=1;
    else if((c-a-b)/d==x && (c-a-b)%d==0) pin=1;
    else if(c/a/b-d==x && c%a==0 && (c/a)%b==0) pin=1;
    else if((c/a-b)/d==x && c%a==0 && (c/a-b)%d==0) pin=1;
    else if((c-a)/b/d==x && (c-a)%b==0 && ((c-a)/b)%d==0) pin=1;
    else if(c/a*b*d==x && c%a==0) pin=1;
    else if(c*a/b*d==x && (c*a)%b==0) pin=1;
    else if(c*a*b/d==x && (c*a*b)%d==0) pin=1;
    else if(c*a/b/d==x && (c*a)%b==0 && (c*a/b)%d==0) pin=1;
    else if(c/a*b/d==x && c%a==0 && (c/a*b)%d==0) pin=1;
    else if(c/a/b*d==x && c%a==0 && (c/a)%b==0) pin=1;
    else if((c+a-b)*d==x) pin=1;
    else if((c-a)*b+d==x) pin=1;
    else if(c*a-b+d==x) pin=1;
    else if((c+a)*b-d==x) pin=1;
    else if(c*a+b-d==x) pin=1;
    else if((c-a+b)*d==x) pin=1;
    else if((c-a)*b/d==x && ((c-a)*b)%d==0) pin=1;
    else if(c*a/b-d==x && (c*a)%b==0) pin=1;
    else if((c/a-b)*d==x && c%a==0) pin=1;
    else if((c-a)/b*d==x && (c-a)%b==0) pin=1;
    else if(c/a*b-d==x && c%a==0) pin=1;
    else if((c*a-b)/d==x && (c*a-b)%d==0) pin=1;
    else if(c*a/b+d==x && (c*a)%b==0) pin=1;
    else if((c/a+b)*d==x && c%a==0) pin=1;
    else if((c+a)/b*d==x && (c+a)%b==0) pin=1;
    else if((c*a+b)/d==x && (c*a+b)%d==0) pin=1;
    else if((c+a)*b/d==x && ((c+a)*b)%d==0) pin=1;
    else if(c/a*b+d==x && c%a==0) pin=1;
    else if((c+a)/b-d==x && (c+a)%b==0) pin=1;
    else if((c-a)/b+d==x && (c-a)%b==0) pin=1;
    else if(c/a-b+d==x && c%a==0) pin=1;
    else if((c-a+b)/d==x && (c-a+b)%d==0) pin=1;
    else if((c+a-b)/d==x && (c+a-b)%d==0) pin=1;
    else if(c/a+b-d==x && c%a==0) pin=1;
    else if(c+d+b-a==x) pin=1;
    else if(c+d-b+a==x) pin=1;
    else if(c-d+b+a==x) pin=1;
    else if(c+d-b-a==x) pin=1;
    else if(c-d+b-a==x) pin=1;
    else if(c-d-b+a==x) pin=1;
    else if(c-d-b-a==x) pin=1;
    else if(c*d*b*a==x) pin=1;
    else if(c/d/b/a==x && c%d==0 && (c/d)%b==0 && (c/d/b)%a==0) pin=1;
    else if((c+d+b)*a==x) pin=1;
    else if((c+d)*b+a==x) pin=1;
    else if(c*d+b+a==x) pin=1;
    else if(c*d*b+a==x) pin=1;
    else if((c*d+b)*a==x) pin=1;
    else if((c+d)*b*a==x) pin=1;
    else if(c*d*b-a==x) pin=1;
    else if((c*d-b)*a==x) pin=1;
    else if((c-d)*b*a==x) pin=1;
    else if(c*d-b-a==x) pin=1;
    else if((c-d)*b-a==x) pin=1;
    else if((c-d-b)*a==x) pin=1;
    else if(c/d+b+a==x && c%d==0) pin=1;
    else if((c+d)/b+a==x && (c+d)%b==0) pin=1;
    else if((c+d+b)/a==x && (c+d+b)%a==0) pin=1;
    else if(c/d/b+a==x && c%d==0 && (c/d)%b==0) pin=1;
    else if((c/d+b)/a==x && c%d==0 && (c/d+b)%a==0) pin=1;
    else if((c+d)/b/a==x && (c+d)%b==0 && ((c+d)/b)%a==0) pin=1;
    else if(c/d-b-a==x && c%d==0) pin=1;
    else if((c-d)/b-a==x && (c-d)%b==0) pin=1;
    else if((c-d-b)/a==x && (c-d-b)%a==0) pin=1;
    else if(c/d/b-a==x && c%d==0 && (c/d)%b==0) pin=1;
    else if((c/d-b)/a==x && c%d==0 && (c/d-b)%a==0) pin=1;
    else if((c-d)/b/a==x && (c-d)%b==0 && ((c-d)/b)%a==0) pin=1;
    else if(c/d*b*a==x && c%d==0) pin=1;
    else if(c*d/b*a==x && (c*d)%b==0) pin=1;
    else if(c*d*b/a==x && (c*d*b)%a==0) pin=1;
    else if(c*d/b/a==x && (c*d)%b==0 && (c*d/b)%a==0) pin=1;
    else if(c/d*b/a==x && c%d==0 && (c/d*b)%a==0) pin=1;
    else if(c/d/b*a==x && c%d==0 && (c/d)%b==0) pin=1;
    else if((c+d-b)*a==x) pin=1;
    else if((c-d)*b+a==x) pin=1;
    else if(c*d-b+a==x) pin=1;
    else if((c+d)*b-a==x) pin=1;
    else if(c*d+b-a==x) pin=1;
    else if((c-d+b)*a==x) pin=1;
    else if((c-d)*b/a==x && ((c-d)*b)%a==0) pin=1;
    else if(c*d/b-a==x && (c*d)%b==0) pin=1;
    else if((c/d-b)*a==x && c%d==0) pin=1;
    else if((c-d)/b*a==x && (c-d)%b==0) pin=1;
    else if(c/d*b-a==x && c%d==0) pin=1;
    else if((c*d-b)/a==x && (c*d-b)%a==0) pin=1;
    else if(c*d/b+a==x && (c*d)%b==0) pin=1;
    else if((c/d+b)*a==x && c%d==0) pin=1;
    else if((c+d)/b*a==x && (c+d)%b==0) pin=1;
    else if((c*d+b)/a==x && (c*d+b)%a==0) pin=1;
    else if((c+d)*b/a==x && ((c+d)*b)%a==0) pin=1;
    else if(c/d*b+a==x && c%d==0) pin=1;
    else if((c+d)/b-a==x && (c+d)%b==0) pin=1;
    else if((c-d)/b+a==x && (c-d)%b==0) pin=1;
    else if(c/d-b+a==x && c%d==0) pin=1;
    else if((c-d+b)/a==x && (c-d+b)%a==0) pin=1;
    else if((c+d-b)/a==x && (c+d-b)%a==0) pin=1;
    else if(c/d+b-a==x && c%d==0) pin=1;
    else if(c+d+a-b==x) pin=1;
    else if(c+d-a+b==x) pin=1;
    else if(c-d+a+b==x) pin=1;
    else if(c+d-a-b==x) pin=1;
    else if(c-d+a-b==x) pin=1;
    else if(c-d-a+b==x) pin=1;
    else if(c-d-a-b==x) pin=1;
    else if(c*d*a*b==x) pin=1;
    else if(c/d/a/b==x && c%d==0 && (c/d)%a==0 && (c/d/a)%b==0) pin=1;
    else if((c+d+a)*b==x) pin=1;
    else if((c+d)*a+b==x) pin=1;
    else if(c*d+a+b==x) pin=1;
    else if(c*d*a+b==x) pin=1;
    else if((c*d+a)*b==x) pin=1;
    else if((c+d)*a*b==x) pin=1;
    else if(c*d*a-b==x) pin=1;
    else if((c*d-a)*b==x) pin=1;
    else if((c-d)*a*b==x) pin=1;
    else if(c*d-a-b==x) pin=1;
    else if((c-d)*a-b==x) pin=1;
    else if((c-d-a)*b==x) pin=1;
    else if(c/d+a+b==x && c%d==0) pin=1;
    else if((c+d)/a+b==x && (c+d)%a==0) pin=1;
    else if((c+d+a)/b==x && (c+d+a)%b==0) pin=1;
    else if(c/d/a+b==x && c%d==0 && (c/d)%a==0) pin=1;
    else if((c/d+a)/b==x && c%d==0 && (c/d+a)%b==0) pin=1;
    else if((c+d)/a/b==x && (c+d)%a==0 && ((c+d)/a)%b==0) pin=1;
    else if(c/d-a-b==x && c%d==0) pin=1;
    else if((c-d)/a-b==x && (c-d)%a==0) pin=1;
    else if((c-d-a)/b==x && (c-d-a)%b==0) pin=1;
    else if(c/d/a-b==x && c%d==0 && (c/d)%a==0) pin=1;
    else if((c/d-a)/b==x && c%d==0 && (c/d-a)%b==0) pin=1;
    else if((c-d)/a/b==x && (c-d)%a==0 && ((c-d)/a)%b==0) pin=1;
    else if(c/d*a*b==x && c%d==0) pin=1;
    else if(c*d/a*b==x && (c*d)%a==0) pin=1;
    else if(c*d*a/b==x && (c*d*a)%b==0) pin=1;
    else if(c*d/a/b==x && (c*d)%a==0 && (c*d/a)%b==0) pin=1;
    else if(c/d*a/b==x && c%d==0 && (c/d*a)%b==0) pin=1;
    else if(c/d/a*b==x && c%d==0 && (c/d)%a==0) pin=1;
    else if((c+d-a)*b==x) pin=1;
    else if((c-d)*a+b==x) pin=1;
    else if(c*d-a+b==x) pin=1;
    else if((c+d)*a-b==x) pin=1;
    else if(c*d+a-b==x) pin=1;
    else if((c-d+a)*b==x) pin=1;
    else if((c-d)*a/b==x && ((c-d)*a)%b==0) pin=1;
    else if(c*d/a-b==x && (c*d)%a==0) pin=1;
    else if((c/d-a)*b==x && c%d==0) pin=1;
    else if((c-d)/a*b==x && (c-d)%a==0) pin=1;
    else if(c/d*a-b==x && c%d==0) pin=1;
    else if((c*d-a)/b==x && (c*d-a)%b==0) pin=1;
    else if(c*d/a+b==x && (c*d)%a==0) pin=1;
    else if((c/d+a)*b==x && c%d==0) pin=1;
    else if((c+d)/a*b==x && (c+d)%a==0) pin=1;
    else if((c*d+a)/b==x && (c*d+a)%b==0) pin=1;
    else if((c+d)*a/b==x && ((c+d)*a)%b==0) pin=1;
    else if(c/d*a+b==x && c%d==0) pin=1;
    else if((c+d)/a-b==x && (c+d)%a==0) pin=1;
    else if((c-d)/a+b==x && (c-d)%a==0) pin=1;
    else if(c/d-a+b==x && c%d==0) pin=1;
    else if((c-d+a)/b==x && (c-d+a)%b==0) pin=1;
    else if((c+d-a)/b==x && (c+d-a)%b==0) pin=1;
    else if(c/d+a-b==x && c%d==0) pin=1;
    else if(d+b+c-a==x) pin=1;
    else if(d+b-c+a==x) pin=1;
    else if(d-b+c+a==x) pin=1;
    else if(d+b-c-a==x) pin=1;
    else if(d-b+c-a==x) pin=1;
    else if(d-b-c+a==x) pin=1;
    else if(d-b-c-a==x) pin=1;
    else if(d*b*c*a==x) pin=1;
    else if(d/b/c/a==x && d%b==0 && (d/b)%c==0 && (d/b/c)%a==0) pin=1;
    else if((d+b+c)*a==x) pin=1;
    else if((d+b)*c+a==x) pin=1;
    else if(d*b+c+a==x) pin=1;
    else if(d*b*c+a==x) pin=1;
    else if((d*b+c)*a==x) pin=1;
    else if((d+b)*c*a==x) pin=1;
    else if(d*b*c-a==x) pin=1;
    else if((d*b-c)*a==x) pin=1;
    else if((d-b)*c*a==x) pin=1;
    else if(d*b-c-a==x) pin=1;
    else if((d-b)*c-a==x) pin=1;
    else if((d-b-c)*a==x) pin=1;
    else if(d/b+c+a==x && d%b==0) pin=1;
    else if((d+b)/c+a==x && (d+b)%c==0) pin=1;
    else if((d+b+c)/a==x && (d+b+c)%a==0) pin=1;
    else if(d/b/c+a==x && d%b==0 && (d/b)%c==0) pin=1;
    else if((d/b+c)/a==x && d%b==0 && (d/b+c)%a==0) pin=1;
    else if((d+b)/c/a==x && (d+b)%c==0 && ((d+b)/c)%a==0) pin=1;
    else if(d/b-c-a==x && d%b==0) pin=1;
    else if((d-b)/c-a==x && (d-b)%c==0) pin=1;
    else if((d-b-c)/a==x && (d-b-c)%a==0) pin=1;
    else if(d/b/c-a==x && d%b==0 && (d/b)%c==0) pin=1;
    else if((d/b-c)/a==x && d%b==0 && (d/b-c)%a==0) pin=1;
    else if((d-b)/c/a==x && (d-b)%c==0 && ((d-b)/c)%a==0) pin=1;
    else if(d/b*c*a==x && d%b==0) pin=1;
    else if(d*b/c*a==x && (d*b)%c==0) pin=1;
    else if(d*b*c/a==x && (d*b*c)%a==0) pin=1;
    else if(d*b/c/a==x && (d*b)%c==0 && (d*b/c)%a==0) pin=1;
    else if(d/b*c/a==x && d%b==0 && (d/b*c)%a==0) pin=1;
    else if(d/b/c*a==x && d%b==0 && (d/b)%c==0) pin=1;
    else if((d+b-c)*a==x) pin=1;
    else if((d-b)*c+a==x) pin=1;
    else if(d*b-c+a==x) pin=1;
    else if((d+b)*c-a==x) pin=1;
    else if(d*b+c-a==x) pin=1;
    else if((d-b+c)*a==x) pin=1;
    else if((d-b)*c/a==x && ((d-b)*c)%a==0) pin=1;
    else if(d*b/c-a==x && (d*b)%c==0) pin=1;
    else if((d/b-c)*a==x && d%b==0) pin=1;
    else if((d-b)/c*a==x && (d-b)%c==0) pin=1;
    else if(d/b*c-a==x && d%b==0) pin=1;
    else if((d*b-c)/a==x && (d*b-c)%a==0) pin=1;
    else if(d*b/c+a==x && (d*b)%c==0) pin=1;
    else if((d/b+c)*a==x && d%b==0) pin=1;
    else if((d+b)/c*a==x && (d+b)%c==0) pin=1;
    else if((d*b+c)/a==x && (d*b+c)%a==0) pin=1;
    else if((d+b)*c/a==x && ((d+b)*c)%a==0) pin=1;
    else if(d/b*c+a==x && d%b==0) pin=1;
    else if((d+b)/c-a==x && (d+b)%c==0) pin=1;
    else if((d-b)/c+a==x && (d-b)%c==0) pin=1;
    else if(d/b-c+a==x && d%b==0) pin=1;
    else if((d-b+c)/a==x && (d-b+c)%a==0) pin=1;
    else if((d+b-c)/a==x && (d+b-c)%a==0) pin=1;
    else if(d/b+c-a==x && d%b==0) pin=1;
    else if(d+a+c-b==x) pin=1;
    else if(d+a-c+b==x) pin=1;
    else if(d-a+c+b==x) pin=1;
    else if(d+a-c-b==x) pin=1;
    else if(d-a+c-b==x) pin=1;
    else if(d-a-c+b==x) pin=1;
    else if(d-a-c-b==x) pin=1;
    else if(d*a*c*b==x) pin=1;
    else if(d/a/c/b==x && d%a==0 && (d/a)%c==0 && (d/a/c)%b==0) pin=1;
    else if((d+a+c)*b==x) pin=1;
    else if((d+a)*c+b==x) pin=1;
    else if(d*a+c+b==x) pin=1;
    else if(d*a*c+b==x) pin=1;
    else if((d*a+c)*b==x) pin=1;
    else if((d+a)*c*b==x) pin=1;
    else if(d*a*c-b==x) pin=1;
    else if((d*a-c)*b==x) pin=1;
    else if((d-a)*c*b==x) pin=1;
    else if(d*a-c-b==x) pin=1;
    else if((d-a)*c-b==x) pin=1;
    else if((d-a-c)*b==x) pin=1;
    else if(d/a+c+b==x && d%a==0) pin=1;
    else if((d+a)/c+b==x && (d+a)%c==0) pin=1;
    else if((d+a+c)/b==x && (d+a+c)%b==0) pin=1;
    else if(d/a/c+b==x && d%a==0 && (d/a)%c==0) pin=1;
    else if((d/a+c)/b==x && d%a==0 && (d/a+c)%b==0) pin=1;
    else if((d+a)/c/b==x && (d+a)%c==0 && ((d+a)/c)%b==0) pin=1;
    else if(d/a-c-b==x && d%a==0) pin=1;
    else if((d-a)/c-b==x && (d-a)%c==0) pin=1;
    else if((d-a-c)/b==x && (d-a-c)%b==0) pin=1;
    else if(d/a/c-b==x && d%a==0 && (d/a)%c==0) pin=1;
    else if((d/a-c)/b==x && d%a==0 && (d/a-c)%b==0) pin=1;
    else if((d-a)/c/b==x && (d-a)%c==0 && ((d-a)/c)%b==0) pin=1;
    else if(d/a*c*b==x && d%a==0) pin=1;
    else if(d*a/c*b==x && (d*a)%c==0) pin=1;
    else if(d*a*c/b==x && (d*a*c)%b==0) pin=1;
    else if(d*a/c/b==x && (d*a)%c==0 && (d*a/c)%b==0) pin=1;
    else if(d/a*c/b==x && d%a==0 && (d/a*c)%b==0) pin=1;
    else if(d/a/c*b==x && d%a==0 && (d/a)%c==0) pin=1;
    else if((d+a-c)*b==x) pin=1;
    else if((d-a)*c+b==x) pin=1;
    else if(d*a-c+b==x) pin=1;
    else if((d+a)*c-b==x) pin=1;
    else if(d*a+c-b==x) pin=1;
    else if((d-a+c)*b==x) pin=1;
    else if((d-a)*c/b==x && ((d-a)*c)%b==0) pin=1;
    else if(d*a/c-b==x && (d*a)%c==0) pin=1;
    else if((d/a-c)*b==x && d%a==0) pin=1;
    else if((d-a)/c*b==x && (d-a)%c==0) pin=1;
    else if(d/a*c-b==x && d%a==0) pin=1;
    else if((d*a-c)/b==x && (d*a-c)%b==0) pin=1;
    else if(d*a/c+b==x && (d*a)%c==0) pin=1;
    else if((d/a+c)*b==x && d%a==0) pin=1;
    else if((d+a)/c*b==x && (d+a)%c==0) pin=1;
    else if((d*a+c)/b==x && (d*a+c)%b==0) pin=1;
    else if((d+a)*c/b==x && ((d+a)*c)%b==0) pin=1;
    else if(d/a*c+b==x && d%a==0) pin=1;
    else if((d+a)/c-b==x && (d+a)%c==0) pin=1;
    else if((d-a)/c+b==x && (d-a)%c==0) pin=1;
    else if(d/a-c+b==x && d%a==0) pin=1;
    else if((d-a+c)/b==x && (d-a+c)%b==0) pin=1;
    else if((d+a-c)/b==x && (d+a-c)%b==0) pin=1;
    else if(d/a+c-b==x && d%a==0) pin=1;
    else if(d+c+a-b==x) pin=1;
    else if(d+c-a+b==x) pin=1;
    else if(d-c+a+b==x) pin=1;
    else if(d+c-a-b==x) pin=1;
    else if(d-c+a-b==x) pin=1;
    else if(d-c-a+b==x) pin=1;
    else if(d-c-a-b==x) pin=1;
    else if(d*c*a*b==x) pin=1;
    else if(d/c/a/b==x && d%c==0 && (d/c)%a==0 && (d/c/a)%b==0) pin=1;
    else if((d+c+a)*b==x) pin=1;
    else if((d+c)*a+b==x) pin=1;
    else if(d*c+a+b==x) pin=1;
    else if(d*c*a+b==x) pin=1;
    else if((d*c+a)*b==x) pin=1;
    else if((d+c)*a*b==x) pin=1;
    else if(d*c*a-b==x) pin=1;
    else if((d*c-a)*b==x) pin=1;
    else if((d-c)*a*b==x) pin=1;
    else if(d*c-a-b==x) pin=1;
    else if((d-c)*a-b==x) pin=1;
    else if((d-c-a)*b==x) pin=1;
    else if(d/c+a+b==x && d%c==0) pin=1;
    else if((d+c)/a+b==x && (d+c)%a==0) pin=1;
    else if((d+c+a)/b==x && (d+c+a)%b==0) pin=1;
    else if(d/c/a+b==x && d%c==0 && (d/c)%a==0) pin=1;
    else if((d/c+a)/b==x && d%c==0 && (d/c+a)%b==0) pin=1;
    else if((d+c)/a/b==x && (d+c)%a==0 && ((d+c)/a)%b==0) pin=1;
    else if(d/c-a-b==x && d%c==0) pin=1;
    else if((d-c)/a-b==x && (d-c)%a==0) pin=1;
    else if((d-c-a)/b==x && (d-c-a)%b==0) pin=1;
    else if(d/c/a-b==x && d%c==0 && (d/c)%a==0) pin=1;
    else if((d/c-a)/b==x && d%c==0 && (d/c-a)%b==0) pin=1;
    else if((d-c)/a/b==x && (d-c)%a==0 && ((d-c)/a)%b==0) pin=1;
    else if(d/c*a*b==x && d%c==0) pin=1;
    else if(d*c/a*b==x && (d*c)%a==0) pin=1;
    else if(d*c*a/b==x && (d*c*a)%b==0) pin=1;
    else if(d*c/a/b==x && (d*c)%a==0 && (d*c/a)%b==0) pin=1;
    else if(d/c*a/b==x && d%c==0 && (d/c*a)%b==0) pin=1;
    else if(d/c/a*b==x && d%c==0 && (d/c)%a==0) pin=1;
    else if((d+c-a)*b==x) pin=1;
    else if((d-c)*a+b==x) pin=1;
    else if(d*c-a+b==x) pin=1;
    else if((d+c)*a-b==x) pin=1;
    else if(d*c+a-b==x) pin=1;
    else if((d-c+a)*b==x) pin=1;
    else if((d-c)*a/b==x && ((d-c)*a)%b==0) pin=1;
    else if(d*c/a-b==x && (d*c)%a==0) pin=1;
    else if((d/c-a)*b==x && d%c==0) pin=1;
    else if((d-c)/a*b==x && (d-c)%a==0) pin=1;
    else if(d/c*a-b==x && d%c==0) pin=1;
    else if((d*c-a)/b==x && (d*c-a)%b==0) pin=1;
    else if(d*c/a+b==x && (d*c)%a==0) pin=1;
    else if((d/c+a)*b==x && d%c==0) pin=1;
    else if((d+c)/a*b==x && (d+c)%a==0) pin=1;
    else if((d*c+a)/b==x && (d*c+a)%b==0) pin=1;
    else if((d+c)*a/b==x && ((d+c)*a)%b==0) pin=1;
    else if(d/c*a+b==x && d%c==0) pin=1;
    else if((d+c)/a-b==x && (d+c)%a==0) pin=1;
    else if((d-c)/a+b==x && (d-c)%a==0) pin=1;
    else if(d/c-a+b==x && d%c==0) pin=1;
    else if((d-c+a)/b==x && (d-c+a)%b==0) pin=1;
    else if((d+c-a)/b==x && (d+c-a)%b==0) pin=1;
    else if(d/c+a-b==x && d%c==0) pin=1;
    else if(d+c+b-a==x) pin=1;
    else if(d+c-b+a==x) pin=1;
    else if(d-c+b+a==x) pin=1;
    else if(d+c-b-a==x) pin=1;
    else if(d-c+b-a==x) pin=1;
    else if(d-c-b+a==x) pin=1;
    else if(d-c-b-a==x) pin=1;
    else if(d*c*b*a==x) pin=1;
    else if(d/c/b/a==x && d%c==0 && (d/c)%b==0 && (d/c/b)%a==0) pin=1;
    else if((d+c+b)*a==x) pin=1;
    else if((d+c)*b+a==x) pin=1;
    else if(d*c+b+a==x) pin=1;
    else if(d*c*b+a==x) pin=1;
    else if((d*c+b)*a==x) pin=1;
    else if((d+c)*b*a==x) pin=1;
    else if(d*c*b-a==x) pin=1;
    else if((d*c-b)*a==x) pin=1;
    else if((d-c)*b*a==x) pin=1;
    else if(d*c-b-a==x) pin=1;
    else if((d-c)*b-a==x) pin=1;
    else if((d-c-b)*a==x) pin=1;
    else if(d/c+b+a==x && d%c==0) pin=1;
    else if((d+c)/b+a==x && (d+c)%b==0) pin=1;
    else if((d+c+b)/a==x && (d+c+b)%a==0) pin=1;
    else if(d/c/b+a==x && d%c==0 && (d/c)%b==0) pin=1;
    else if((d/c+b)/a==x && d%c==0 && (d/c+b)%a==0) pin=1;
    else if((d+c)/b/a==x && (d+c)%b==0 && ((d+c)/b)%a==0) pin=1;
    else if(d/c-b-a==x && d%c==0) pin=1;
    else if((d-c)/b-a==x && (d-c)%b==0) pin=1;
    else if((d-c-b)/a==x && (d-c-b)%a==0) pin=1;
    else if(d/c/b-a==x && d%c==0 && (d/c)%b==0) pin=1;
    else if((d/c-b)/a==x && d%c==0 && (d/c-b)%a==0) pin=1;
    else if((d-c)/b/a==x && (d-c)%b==0 && ((d-c)/b)%a==0) pin=1;
    else if(d/c*b*a==x && d%c==0) pin=1;
    else if(d*c/b*a==x && (d*c)%b==0) pin=1;
    else if(d*c*b/a==x && (d*c*b)%a==0) pin=1;
    else if(d*c/b/a==x && (d*c)%b==0 && (d*c/b)%a==0) pin=1;
    else if(d/c*b/a==x && d%c==0 && (d/c*b)%a==0) pin=1;
    else if(d/c/b*a==x && d%c==0 && (d/c)%b==0) pin=1;
    else if((d+c-b)*a==x) pin=1;
    else if((d-c)*b+a==x) pin=1;
    else if(d*c-b+a==x) pin=1;
    else if((d+c)*b-a==x) pin=1;
    else if(d*c+b-a==x) pin=1;
    else if((d-c+b)*a==x) pin=1;
    else if((d-c)*b/a==x && ((d-c)*b)%a==0) pin=1;
    else if(d*c/b-a==x && (d*c)%b==0) pin=1;
    else if((d/c-b)*a==x && d%c==0) pin=1;
    else if((d-c)/b*a==x && (d-c)%b==0) pin=1;
    else if(d/c*b-a==x && d%c==0) pin=1;
    else if((d*c-b)/a==x && (d*c-b)%a==0) pin=1;
    else if(d*c/b+a==x && (d*c)%b==0) pin=1;
    else if((d/c+b)*a==x && d%c==0) pin=1;
    else if((d+c)/b*a==x && (d+c)%b==0) pin=1;
    else if((d*c+b)/a==x && (d*c+b)%a==0) pin=1;
    else if((d+c)*b/a==x && ((d+c)*b)%a==0) pin=1;
    else if(d/c*b+a==x && d%c==0) pin=1;
    else if((d+c)/b-a==x && (d+c)%b==0) pin=1;
    else if((d-c)/b+a==x && (d-c)%b==0) pin=1;
    else if(d/c-b+a==x && d%c==0) pin=1;
    else if((d-c+b)/a==x && (d-c+b)%a==0) pin=1;
    else if((d+c-b)/a==x && (d+c-b)%a==0) pin=1;
    else if(d/c+b-a==x && d%c==0) pin=1;
    else if(d+b+a-c==x) pin=1;
    else if(d+b-a+c==x) pin=1;
    else if(d-b+a+c==x) pin=1;
    else if(d+b-a-c==x) pin=1;
    else if(d-b+a-c==x) pin=1;
    else if(d-b-a+c==x) pin=1;
    else if(d-b-a-c==x) pin=1;
    else if(d*b*a*c==x) pin=1;
    else if(d/b/a/c==x && d%b==0 && (d/b)%a==0 && (d/b/a)%c==0) pin=1;
    else if((d+b+a)*c==x) pin=1;
    else if((d+b)*a+c==x) pin=1;
    else if(d*b+a+c==x) pin=1;
    else if(d*b*a+c==x) pin=1;
    else if((d*b+a)*c==x) pin=1;
    else if((d+b)*a*c==x) pin=1;
    else if(d*b*a-c==x) pin=1;
    else if((d*b-a)*c==x) pin=1;
    else if((d-b)*a*c==x) pin=1;
    else if(d*b-a-c==x) pin=1;
    else if((d-b)*a-c==x) pin=1;
    else if((d-b-a)*c==x) pin=1;
    else if(d/b+a+c==x && d%b==0) pin=1;
    else if((d+b)/a+c==x && (d+b)%a==0) pin=1;
    else if((d+b+a)/c==x && (d+b+a)%c==0) pin=1;
    else if(d/b/a+c==x && d%b==0 && (d/b)%a==0) pin=1;
    else if((d/b+a)/c==x && d%b==0 && (d/b+a)%c==0) pin=1;
    else if((d+b)/a/c==x && (d+b)%a==0 && ((d+b)/a)%c==0) pin=1;
    else if(d/b-a-c==x && d%b==0) pin=1;
    else if((d-b)/a-c==x && (d-b)%a==0) pin=1;
    else if((d-b-a)/c==x && (d-b-a)%c==0) pin=1;
    else if(d/b/a-c==x && d%b==0 && (d/b)%a==0) pin=1;
    else if((d/b-a)/c==x && d%b==0 && (d/b-a)%c==0) pin=1;
    else if((d-b)/a/c==x && (d-b)%a==0 && ((d-b)/a)%c==0) pin=1;
    else if(d/b*a*c==x && d%b==0) pin=1;
    else if(d*b/a*c==x && (d*b)%a==0) pin=1;
    else if(d*b*a/c==x && (d*b*a)%c==0) pin=1;
    else if(d*b/a/c==x && (d*b)%a==0 && (d*b/a)%c==0) pin=1;
    else if(d/b*a/c==x && d%b==0 && (d/b*a)%c==0) pin=1;
    else if(d/b/a*c==x && d%b==0 && (d/b)%a==0) pin=1;
    else if((d+b-a)*c==x) pin=1;
    else if((d-b)*a+c==x) pin=1;
    else if(d*b-a+c==x) pin=1;
    else if((d+b)*a-c==x) pin=1;
    else if(d*b+a-c==x) pin=1;
    else if((d-b+a)*c==x) pin=1;
    else if((d-b)*a/c==x && ((d-b)*a)%c==0) pin=1;
    else if(d*b/a-c==x && (d*b)%a==0) pin=1;
    else if((d/b-a)*c==x && d%b==0) pin=1;
    else if((d-b)/a*c==x && (d-b)%a==0) pin=1;
    else if(d/b*a-c==x && d%b==0) pin=1;
    else if((d*b-a)/c==x && (d*b-a)%c==0) pin=1;
    else if(d*b/a+c==x && (d*b)%a==0) pin=1;
    else if((d/b+a)*c==x && d%b==0) pin=1;
    else if((d+b)/a*c==x && (d+b)%a==0) pin=1;
    else if((d*b+a)/c==x && (d*b+a)%c==0) pin=1;
    else if((d+b)*a/c==x && ((d+b)*a)%c==0) pin=1;
    else if(d/b*a+c==x && d%b==0) pin=1;
    else if((d+b)/a-c==x && (d+b)%a==0) pin=1;
    else if((d-b)/a+c==x && (d-b)%a==0) pin=1;
    else if(d/b-a+c==x && d%b==0) pin=1;
    else if((d-b+a)/c==x && (d-b+a)%c==0) pin=1;
    else if((d+b-a)/c==x && (d+b-a)%c==0) pin=1;
    else if(d/b+a-c==x && d%b==0) pin=1;
    else if(d+a+b-c==x) pin=1;
    else if(d+a-b+c==x) pin=1;
    else if(d-a+b+c==x) pin=1;
    else if(d+a-b-c==x) pin=1;
    else if(d-a+b-c==x) pin=1;
    else if(d-a-b+c==x) pin=1;
    else if(d-a-b-c==x) pin=1;
    else if(d*a*b*c==x) pin=1;
    else if(d/a/b/c==x && d%a==0 && (d/a)%b==0 && (d/a/b)%c==0) pin=1;
    else if((d+a+b)*c==x) pin=1;
    else if((d+a)*b+c==x) pin=1;
    else if(d*a+b+c==x) pin=1;
    else if(d*a*b+c==x) pin=1;
    else if((d*a+b)*c==x) pin=1;
    else if((d+a)*b*c==x) pin=1;
    else if(d*a*b-c==x) pin=1;
    else if((d*a-b)*c==x) pin=1;
    else if((d-a)*b*c==x) pin=1;
    else if(d*a-b-c==x) pin=1;
    else if((d-a)*b-c==x) pin=1;
    else if((d-a-b)*c==x) pin=1;
    else if(d/a+b+c==x && d%a==0) pin=1;
    else if((d+a)/b+c==x && (d+a)%b==0) pin=1;
    else if((d+a+b)/c==x && (d+a+b)%c==0) pin=1;
    else if(d/a/b+c==x && d%a==0 && (d/a)%b==0) pin=1;
    else if((d/a+b)/c==x && d%a==0 && (d/a+b)%c==0) pin=1;
    else if((d+a)/b/c==x && (d+a)%b==0 && ((d+a)/b)%c==0) pin=1;
    else if(d/a-b-c==x && d%a==0) pin=1;
    else if((d-a)/b-c==x && (d-a)%b==0) pin=1;
    else if((d-a-b)/c==x && (d-a-b)%c==0) pin=1;
    else if(d/a/b-c==x && d%a==0 && (d/a)%b==0) pin=1;
    else if((d/a-b)/c==x && d%a==0 && (d/a-b)%c==0) pin=1;
    else if((d-a)/b/c==x && (d-a)%b==0 && ((d-a)/b)%c==0) pin=1;
    else if(d/a*b*c==x && d%a==0) pin=1;
    else if(d*a/b*c==x && (d*a)%b==0) pin=1;
    else if(d*a*b/c==x && (d*a*b)%c==0) pin=1;
    else if(d*a/b/c==x && (d*a)%b==0 && (d*a/b)%c==0) pin=1;
    else if(d/a*b/c==x && d%a==0 && (d/a*b)%c==0) pin=1;
    else if(d/a/b*c==x && d%a==0 && (d/a)%b==0) pin=1;
    else if((d+a-b)*c==x) pin=1;
    else if((d-a)*b+c==x) pin=1;
    else if(d*a-b+c==x) pin=1;
    else if((d+a)*b-c==x) pin=1;
    else if(d*a+b-c==x) pin=1;
    else if((d-a+b)*c==x) pin=1;
    else if((d-a)*b/c==x && ((d-a)*b)%c==0) pin=1;
    else if(d*a/b-c==x && (d*a)%b==0) pin=1;
    else if((d/a-b)*c==x && d%a==0) pin=1;
    else if((d-a)/b*c==x && (d-a)%b==0) pin=1;
    else if(d/a*b-c==x && d%a==0) pin=1;
    else if((d*a-b)/c==x && (d*a-b)%c==0) pin=1;
    else if(d*a/b+c==x && (d*a)%b==0) pin=1;
    else if((d/a+b)*c==x && d%a==0) pin=1;
    else if((d+a)/b*c==x && (d+a)%b==0) pin=1;
    else if((d*a+b)/c==x && (d*a+b)%c==0) pin=1;
    else if((d+a)*b/c==x && ((d+a)*b)%c==0) pin=1;
    else if(d/a*b+c==x && d%a==0) pin=1;
    else if((d+a)/b-c==x && (d+a)%b==0) pin=1;
    else if((d-a)/b+c==x && (d-a)%b==0) pin=1;
    else if(d/a-b+c==x && d%a==0) pin=1;
    else if((d-a+b)/c==x && (d-a+b)%c==0) pin=1;
    else if((d+a-b)/c==x && (d+a-b)%c==0) pin=1;
    else if(d/a+b-c==x && d%a==0) pin=1;
    else if((a+b)*(c+d)==x) pin=1;
    else if((a+c)*(b+d)==x) pin=1;
    else if((a+d)*(c+b)==x) pin=1;
    else if((a-b)*(c-d)==x) pin=1;
    else if((b-a)*(c-d)==x) pin=1;
    else if((a-b)*(d-c)==x) pin=1;
    else if((b-a)*(d-c)==x) pin=1;
    else if((a-c)*(b-d)==x) pin=1;
    else if((c-a)*(b-d)==x) pin=1;
    else if((a-c)*(d-b)==x) pin=1;
    else if((c-a)*(d-b)==x) pin=1;
    else if((a-d)*(c-b)==x) pin=1;
    else if((d-a)*(c-b)==x) pin=1;
    else if((a-d)*(b-c)==x) pin=1;
    else if((d-a)*(b-c)==x) pin=1;
    else if((a+b)/(c+d)==x && (a+b)%(c+d)==0) pin=1;
    else if((a+c)/(b+d)==x && (a+c)%(b+d)==0) pin=1;
    else if((a+d)/(c+b)==x && (a+d)%(c+b)==0) pin=1;
    else if((a-b)/(c-d)==x && (a-b)%(c-d)==0) pin=1;
    else if((b-a)/(c-d)==x && (b-a)%(c-d)==0) pin=1;
    else if((a-b)/(d-c)==x && (a-b)%(d-c)==0) pin=1;
    else if((b-a)/(d-c)==x && (b-a)%(d-c)==0) pin=1;
    else if((a-c)/(b-d)==x && (a-c)%(b-d)==0) pin=1;
    else if((c-a)/(b-d)==x && (c-a)%(b-d)==0) pin=1;
    else if((a-c)/(d-b)==x && (a-c)%(d-b)==0) pin=1;
    else if((c-a)/(d-b)==x && (c-a)%(d-b)==0) pin=1;
    else if((a-d)/(c-b)==x && (a-d)%(c-b)==0) pin=1;
    else if((d-a)/(c-b)==x && (d-a)%(c-b)==0) pin=1;
    else if((a-d)/(b-c)==x && (a-d)%(b-c)==0) pin=1;
    else if((d-a)/(b-c)==x && (d-a)%(b-c)==0) pin=1;
    
    return pin;
}
//0-10できるかな？？
int main(void)
{
    int i,finres;
    int a,b,c,d;
    scanf("%d %d %d %d",&a,&b,&c,&d);

    for(i=0;i<=10;i++)
    {
        finres=check(i,a,b,c,d);
        if(finres==1) printf("%d:OK\n",i);
        else printf("%d:NOT OK\n",i);
    }
    return 0;
}